// @generated by protoc-gen-es v2.14.0
// @generated from file common.proto (package metacore.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file common.proto.
 */
export declare const file_common: GenFile;

/**
 * Every cross-module message carries this so a consumer can detect a schema it was not built for.
 *
 * @generated from message metacore.common.v1.SchemaVersion
 */
export declare type SchemaVersion = Message<"metacore.common.v1.SchemaVersion"> & {
  /**
   * @generated from field: uint32 major = 1;
   */
  major: number;

  /**
   * @generated from field: uint32 minor = 2;
   */
  minor: number;
};

/**
 * Describes the message metacore.common.v1.SchemaVersion.
 * Use `create(SchemaVersionSchema)` to create a new message.
 */
export declare const SchemaVersionSchema: GenMessage<SchemaVersion>;

/**
 * Per-feature missingness mask accompanying any fused observation vector.
 *
 * @generated from message metacore.common.v1.QualityMask
 */
export declare type QualityMask = Message<"metacore.common.v1.QualityMask"> & {
  /**
   * @generated from field: repeated metacore.common.v1.Quality per_feature = 1;
   */
  perFeature: Quality[];

  /**
   * convenience: share of features with QUALITY_OBSERVED
   *
   * @generated from field: float observed_fraction = 2;
   */
  observedFraction: number;
};

/**
 * Describes the message metacore.common.v1.QualityMask.
 * Use `create(QualityMaskSchema)` to create a new message.
 */
export declare const QualityMaskSchema: GenMessage<QualityMask>;

/**
 * Identifies a replayable episode from the shared ID/OOD scenario library (owner: M1).
 *
 * @generated from message metacore.common.v1.ScenarioRef
 */
export declare type ScenarioRef = Message<"metacore.common.v1.ScenarioRef"> & {
  /**
   * e.g. "ditwah-2025-delft"
   *
   * @generated from field: string scenario_id = 1;
   */
  scenarioId: string;

  /**
   * @generated from field: string library_version = 2;
   */
  libraryVersion: string;

  /**
   * label used for M2's OOD evaluation
   *
   * @generated from field: bool out_of_distribution = 3;
   */
  outOfDistribution: boolean;
};

/**
 * Describes the message metacore.common.v1.ScenarioRef.
 * Use `create(ScenarioRefSchema)` to create a new message.
 */
export declare const ScenarioRefSchema: GenMessage<ScenarioRef>;

/**
 * @generated from message metacore.common.v1.Envelope
 */
export declare type Envelope = Message<"metacore.common.v1.Envelope"> & {
  /**
   * @generated from field: metacore.common.v1.SchemaVersion schema_version = 1;
   */
  schemaVersion?: SchemaVersion | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp emitted_at = 2;
   */
  emittedAt?: Timestamp | undefined;

  /**
   * "module1", "module2", ...
   *
   * @generated from field: string producer = 3;
   */
  producer: string;

  /**
   * set during replay; empty in live operation
   *
   * @generated from field: metacore.common.v1.ScenarioRef scenario = 4;
   */
  scenario?: ScenarioRef | undefined;

  /**
   * correlates one step across all four modules
   *
   * @generated from field: string trace_id = 5;
   */
  traceId: string;
};

/**
 * Describes the message metacore.common.v1.Envelope.
 * Use `create(EnvelopeSchema)` to create a new message.
 */
export declare const EnvelopeSchema: GenMessage<Envelope>;

/**
 * @generated from message metacore.common.v1.Health
 */
export declare type Health = Message<"metacore.common.v1.Health"> & {
  /**
   * @generated from field: bool ready = 1;
   */
  ready: boolean;

  /**
   * @generated from field: string detail = 2;
   */
  detail: string;

  /**
   * @generated from field: double last_step_latency_ms = 3;
   */
  lastStepLatencyMs: number;
};

/**
 * Describes the message metacore.common.v1.Health.
 * Use `create(HealthSchema)` to create a new message.
 */
export declare const HealthSchema: GenMessage<Health>;

/**
 * Data-quality flags travel with the state, never stripped. Module 2's epistemic uncertainty
 * depends on being able to see a gap; imputed data presented as observed would hide it.
 *
 * @generated from enum metacore.common.v1.Quality
 */
export enum Quality {
  /**
   * @generated from enum value: QUALITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * measured
   *
   * @generated from enum value: QUALITY_OBSERVED = 1;
   */
  OBSERVED = 1,

  /**
   * filled, and explicitly marked as filled
   *
   * @generated from enum value: QUALITY_INTERPOLATED = 2;
   */
  INTERPOLATED = 2,

  /**
   * absent — downstream must treat as unknown, not as zero
   *
   * @generated from enum value: QUALITY_MISSING = 3;
   */
  MISSING = 3,

  /**
   * last known value, past its freshness budget
   *
   * @generated from enum value: QUALITY_STALE = 4;
   */
  STALE = 4,
}

/**
 * Describes the enum metacore.common.v1.Quality.
 */
export declare const QualitySchema: GenEnum<Quality>;

