// @generated by protoc-gen-es v2.14.0
// @generated from file common.proto (package metacore.common.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file common.proto.
 */
export const file_common = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SEm1ldGFjb3JlLmNvbW1vbi52MSItCg1TY2hlbWFWZXJzaW9uEg0KBW1ham9yGAEgASgNEg0KBW1pbm9yGAIgASgNIloKC1F1YWxpdHlNYXNrEjAKC3Blcl9mZWF0dXJlGAEgAygOMhsubWV0YWNvcmUuY29tbW9uLnYxLlF1YWxpdHkSGQoRb2JzZXJ2ZWRfZnJhY3Rpb24YAiABKAIiWAoLU2NlbmFyaW9SZWYSEwoLc2NlbmFyaW9faWQYASABKAkSFwoPbGlicmFyeV92ZXJzaW9uGAIgASgJEhsKE291dF9vZl9kaXN0cmlidXRpb24YAyABKAgizAEKCEVudmVsb3BlEjkKDnNjaGVtYV92ZXJzaW9uGAEgASgLMiEubWV0YWNvcmUuY29tbW9uLnYxLlNjaGVtYVZlcnNpb24SLgoKZW1pdHRlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEAoIcHJvZHVjZXIYAyABKAkSMQoIc2NlbmFyaW8YBCABKAsyHy5tZXRhY29yZS5jb21tb24udjEuU2NlbmFyaW9SZWYSEAoIdHJhY2VfaWQYBSABKAkiRQoGSGVhbHRoEg0KBXJlYWR5GAEgASgIEg4KBmRldGFpbBgCIAEoCRIcChRsYXN0X3N0ZXBfbGF0ZW5jeV9tcxgDIAEoASp6CgdRdWFsaXR5EhcKE1FVQUxJVFlfVU5TUEVDSUZJRUQQABIUChBRVUFMSVRZX09CU0VSVkVEEAESGAoUUVVBTElUWV9JTlRFUlBPTEFURUQQAhITCg9RVUFMSVRZX01JU1NJTkcQAxIRCg1RVUFMSVRZX1NUQUxFEARCxAEKFmNvbS5tZXRhY29yZS5jb21tb24udjFCC0NvbW1vblByb3RvUAFaM2dpdGh1Yi5jb20vbWV0YWNvcmUvY29udHJhY3RzL2dvL2NvbW1vbi92MTtjb21tb252MaICA01DWKoCEk1ldGFjb3JlLkNvbW1vbi5WMcoCEk1ldGFjb3JlXENvbW1vblxWMeICHk1ldGFjb3JlXENvbW1vblxWMVxHUEJNZXRhZGF0YeoCFE1ldGFjb3JlOjpDb21tb246OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message metacore.common.v1.SchemaVersion.
 * Use `create(SchemaVersionSchema)` to create a new message.
 */
export const SchemaVersionSchema = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * Describes the message metacore.common.v1.QualityMask.
 * Use `create(QualityMaskSchema)` to create a new message.
 */
export const QualityMaskSchema = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * Describes the message metacore.common.v1.ScenarioRef.
 * Use `create(ScenarioRefSchema)` to create a new message.
 */
export const ScenarioRefSchema = /*@__PURE__*/
  messageDesc(file_common, 2);

/**
 * Describes the message metacore.common.v1.Envelope.
 * Use `create(EnvelopeSchema)` to create a new message.
 */
export const EnvelopeSchema = /*@__PURE__*/
  messageDesc(file_common, 3);

/**
 * Describes the message metacore.common.v1.Health.
 * Use `create(HealthSchema)` to create a new message.
 */
export const HealthSchema = /*@__PURE__*/
  messageDesc(file_common, 4);

/**
 * Describes the enum metacore.common.v1.Quality.
 */
export const QualitySchema = /*@__PURE__*/
  enumDesc(file_common, 0);

/**
 * Data-quality flags travel with the state, never stripped. Module 2's epistemic uncertainty
 * depends on being able to see a gap; imputed data presented as observed would hide it.
 *
 * @generated from enum metacore.common.v1.Quality
 */
export const Quality = /*@__PURE__*/
  tsEnum(QualitySchema);

