// @generated by protoc-gen-es v2.14.0
// @generated from file module3.proto (package metacore.module3.v1, syntax proto3)
/* eslint-disable */

// Module 3 — Cost-Aware Metacognitive Gating & Meta-Policy.
// Owner: Saabir S. (IT23432598). Consumer: M4.

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Envelope, HealthSchema, ScenarioRef } from "./common_pb";

/**
 * Describes the file module3.proto.
 */
export declare const file_module3: GenFile;

/**
 * The single action emitted per step, from either System 1 or System 2. Every field is something
 * M4 can apply to the digital twin — nothing here is advisory.
 *
 * @generated from message metacore.module3.v1.ProposedControlAction
 */
export declare type ProposedControlAction = Message<"metacore.module3.v1.ProposedControlAction"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: string action_id = 2;
   */
  actionId: string;

  /**
   * @generated from field: metacore.module3.v1.ProcessPath origin = 3;
   */
  origin: ProcessPath;

  /**
   * @generated from field: repeated metacore.module3.v1.BreakerCommand breakers = 4;
   */
  breakers: BreakerCommand[];

  /**
   * @generated from field: repeated metacore.module3.v1.LoadShedCommand load_shed = 5;
   */
  loadShed: LoadShedCommand[];

  /**
   * @generated from field: repeated metacore.module3.v1.DispatchSetpoint dispatch = 6;
   */
  dispatch: DispatchSetpoint[];

  /**
   * short human-readable summary for the dashboard
   *
   * @generated from field: string rationale = 7;
   */
  rationale: string;
};

/**
 * Describes the message metacore.module3.v1.ProposedControlAction.
 * Use `create(ProposedControlActionSchema)` to create a new message.
 */
export declare const ProposedControlActionSchema: GenMessage<ProposedControlAction>;

/**
 * @generated from message metacore.module3.v1.BreakerCommand
 */
export declare type BreakerCommand = Message<"metacore.module3.v1.BreakerCommand"> & {
  /**
   * @generated from field: string edge_id = 1;
   */
  edgeId: string;

  /**
   * @generated from field: bool closed = 2;
   */
  closed: boolean;
};

/**
 * Describes the message metacore.module3.v1.BreakerCommand.
 * Use `create(BreakerCommandSchema)` to create a new message.
 */
export declare const BreakerCommandSchema: GenMessage<BreakerCommand>;

/**
 * @generated from message metacore.module3.v1.LoadShedCommand
 */
export declare type LoadShedCommand = Message<"metacore.module3.v1.LoadShedCommand"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * 0..1
   *
   * @generated from field: float shed_fraction = 2;
   */
  shedFraction: number;

  /**
   * 1 = most critical, never shed before higher tiers
   *
   * @generated from field: uint32 priority_tier = 3;
   */
  priorityTier: number;
};

/**
 * Describes the message metacore.module3.v1.LoadShedCommand.
 * Use `create(LoadShedCommandSchema)` to create a new message.
 */
export declare const LoadShedCommandSchema: GenMessage<LoadShedCommand>;

/**
 * @generated from message metacore.module3.v1.DispatchSetpoint
 */
export declare type DispatchSetpoint = Message<"metacore.module3.v1.DispatchSetpoint"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: double p_kw = 2;
   */
  pKw: number;

  /**
   * @generated from field: double q_kvar = 3;
   */
  qKvar: number;
};

/**
 * Describes the message metacore.module3.v1.DispatchSetpoint.
 * Use `create(DispatchSetpointSchema)` to create a new message.
 */
export declare const DispatchSetpointSchema: GenMessage<DispatchSetpoint>;

/**
 * Emitted alongside every action for audit, ablation and the dashboard gating timeline.
 *
 * @generated from message metacore.module3.v1.GatingDecision
 */
export declare type GatingDecision = Message<"metacore.module3.v1.GatingDecision"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: string action_id = 2;
   */
  actionId: string;

  /**
   * @generated from field: metacore.module3.v1.ProcessPath chosen = 3;
   */
  chosen: ProcessPath;

  /**
   * @generated from field: float epistemic_at_decision = 4;
   */
  epistemicAtDecision: number;

  /**
   * @generated from field: float expected_survival_benefit = 5;
   */
  expectedSurvivalBenefit: number;

  /**
   * @generated from field: float deliberation_cost = 6;
   */
  deliberationCost: number;

  /**
   * @generated from field: double latency_ms = 7;
   */
  latencyMs: number;

  /**
   * true when System 1 was taken because the budget ran out
   *
   * @generated from field: bool budget_exhausted_fallback = 8;
   */
  budgetExhaustedFallback: boolean;
};

/**
 * Describes the message metacore.module3.v1.GatingDecision.
 * Use `create(GatingDecisionSchema)` to create a new message.
 */
export declare const GatingDecisionSchema: GenMessage<GatingDecision>;

/**
 * @generated from message metacore.module3.v1.GatingRequest
 */
export declare type GatingRequest = Message<"metacore.module3.v1.GatingRequest"> & {
  /**
   * @generated from field: metacore.common.v1.ScenarioRef scenario = 1;
   */
  scenario?: ScenarioRef | undefined;
};

/**
 * Describes the message metacore.module3.v1.GatingRequest.
 * Use `create(GatingRequestSchema)` to create a new message.
 */
export declare const GatingRequestSchema: GenMessage<GatingRequest>;

/**
 * @generated from message metacore.module3.v1.HealthRequest
 */
export declare type HealthRequest = Message<"metacore.module3.v1.HealthRequest"> & {
};

/**
 * Describes the message metacore.module3.v1.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export declare const HealthRequestSchema: GenMessage<HealthRequest>;

/**
 * @generated from enum metacore.module3.v1.ProcessPath
 */
export enum ProcessPath {
  /**
   * @generated from enum value: PROCESS_PATH_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * fast rule-based reactive path
   *
   * @generated from enum value: PROCESS_PATH_SYSTEM1 = 1;
   */
  SYSTEM1 = 1,

  /**
   * deliberative survival optimisation
   *
   * @generated from enum value: PROCESS_PATH_SYSTEM2 = 2;
   */
  SYSTEM2 = 2,
}

/**
 * Describes the enum metacore.module3.v1.ProcessPath.
 */
export declare const ProcessPathSchema: GenEnum<ProcessPath>;

/**
 * @generated from service metacore.module3.v1.GatingService
 */
export declare const GatingService: GenService<{
  /**
   * @generated from rpc metacore.module3.v1.GatingService.StreamAction
   */
  streamAction: {
    methodKind: "server_streaming";
    input: typeof GatingRequestSchema;
    output: typeof ProposedControlActionSchema;
  },
  /**
   * @generated from rpc metacore.module3.v1.GatingService.StreamDecision
   */
  streamDecision: {
    methodKind: "server_streaming";
    input: typeof GatingRequestSchema;
    output: typeof GatingDecisionSchema;
  },
  /**
   * @generated from rpc metacore.module3.v1.GatingService.Health
   */
  health: {
    methodKind: "unary";
    input: typeof HealthRequestSchema;
    output: typeof HealthSchema;
  },
}>;

