// @generated by protoc-gen-es v2.14.0
// @generated from file module1.proto (package metacore.module1.v1, syntax proto3)
/* eslint-disable */

// Module 1 — Multi-Modal Spatiotemporal State Representation.
// Owner: Zayan M.F.M (IT23248212). Consumers: M2 (state), M3 (system context), M4 (topology).

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Envelope, HealthSchema, QualityMask, ScenarioRef } from "./common_pb";

/**
 * Describes the file module1.proto.
 */
export declare const file_module1: GenFile;

/**
 * ---------------------------------------------------------------- M1 -> M2
 * The state representation. Frozen before the live stream exists so M2's evidential head can be
 * sized against a real schema rather than a guess.
 *
 * @generated from message metacore.module1.v1.StateRepresentation
 */
export declare type StateRepresentation = Message<"metacore.module1.v1.StateRepresentation"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: uint32 node_count = 2;
   */
  nodeCount: number;

  /**
   * @generated from field: uint32 embedding_dim = 3;
   */
  embeddingDim: number;

  /**
   * Flattened row-major [node_count x embedding_dim] learned node embedding.
   *
   * @generated from field: repeated float node_embedding = 4;
   */
  nodeEmbedding: number[];

  /**
   * Optional pooled graph-level embedding.
   *
   * @generated from field: repeated float graph_embedding = 5;
   */
  graphEmbedding: number[];

  /**
   * Engineered features kept alongside the embedding so downstream ablations can use either.
   *
   * @generated from field: repeated string feature_names = 6;
   */
  featureNames: string[];

  /**
   * [node_count x len(feature_names)]
   *
   * @generated from field: repeated float node_features = 7;
   */
  nodeFeatures: number[];

  /**
   * @generated from field: metacore.common.v1.QualityMask quality = 8;
   */
  quality?: QualityMask | undefined;

  /**
   * True when one or more modalities are absent (e.g. comms blackout). Never silently imputed.
   *
   * @generated from field: bool degraded = 9;
   */
  degraded: boolean;
};

/**
 * Describes the message metacore.module1.v1.StateRepresentation.
 * Use `create(StateRepresentationSchema)` to create a new message.
 */
export declare const StateRepresentationSchema: GenMessage<StateRepresentation>;

/**
 * ---------------------------------------------------------------- M1 -> M4
 * The canonical network model. M1 and M4 must instantiate an identical physical state, so the
 * topology is owned in one place and versioned.
 *
 * @generated from message metacore.module1.v1.GridTopology
 */
export declare type GridTopology = Message<"metacore.module1.v1.GridTopology"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * e.g. "delft-3island-v1"
   *
   * @generated from field: string topology_id = 2;
   */
  topologyId: string;

  /**
   * @generated from field: string opendss_master_file = 3;
   */
  opendssMasterFile: string;

  /**
   * @generated from field: repeated metacore.module1.v1.Node nodes = 4;
   */
  nodes: Node[];

  /**
   * @generated from field: repeated metacore.module1.v1.Edge edges = 5;
   */
  edges: Edge[];
};

/**
 * Describes the message metacore.module1.v1.GridTopology.
 * Use `create(GridTopologySchema)` to create a new message.
 */
export declare const GridTopologySchema: GenMessage<GridTopology>;

/**
 * @generated from message metacore.module1.v1.Node
 */
export declare type Node = Message<"metacore.module1.v1.Node"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: metacore.module1.v1.AssetType asset_type = 2;
   */
  assetType: AssetType;

  /**
   * @generated from field: double nominal_kv = 3;
   */
  nominalKv: number;

  /**
   * @generated from field: bool critical_load = 4;
   */
  criticalLoad: boolean;

  /**
   * Published as arbitrary spatial offsets, never true coordinates (data governance).
   *
   * @generated from field: double x_offset = 5;
   */
  xOffset: number;

  /**
   * @generated from field: double y_offset = 6;
   */
  yOffset: number;
};

/**
 * Describes the message metacore.module1.v1.Node.
 * Use `create(NodeSchema)` to create a new message.
 */
export declare const NodeSchema: GenMessage<Node>;

/**
 * @generated from message metacore.module1.v1.Edge
 */
export declare type Edge = Message<"metacore.module1.v1.Edge"> & {
  /**
   * @generated from field: string edge_id = 1;
   */
  edgeId: string;

  /**
   * @generated from field: string from_node = 2;
   */
  fromNode: string;

  /**
   * @generated from field: string to_node = 3;
   */
  toNode: string;

  /**
   * @generated from field: double length_km = 4;
   */
  lengthKm: number;

  /**
   * @generated from field: double ampacity_a = 5;
   */
  ampacityA: number;
};

/**
 * Describes the message metacore.module1.v1.Edge.
 * Use `create(EdgeSchema)` to create a new message.
 */
export declare const EdgeSchema: GenMessage<Edge>;

/**
 * The electrical snapshot M4 loads into its digital twin.
 *
 * @generated from message metacore.module1.v1.GridStateSnapshot
 */
export declare type GridStateSnapshot = Message<"metacore.module1.v1.GridStateSnapshot"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: string topology_id = 2;
   */
  topologyId: string;

  /**
   * @generated from field: repeated metacore.module1.v1.NodeState node_states = 3;
   */
  nodeStates: NodeState[];

  /**
   * @generated from field: double update_period_s = 4;
   */
  updatePeriodS: number;
};

/**
 * Describes the message metacore.module1.v1.GridStateSnapshot.
 * Use `create(GridStateSnapshotSchema)` to create a new message.
 */
export declare const GridStateSnapshotSchema: GenMessage<GridStateSnapshot>;

/**
 * @generated from message metacore.module1.v1.NodeState
 */
export declare type NodeState = Message<"metacore.module1.v1.NodeState"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: double voltage_pu = 2;
   */
  voltagePu: number;

  /**
   * @generated from field: double p_kw = 3;
   */
  pKw: number;

  /**
   * @generated from field: double q_kvar = 4;
   */
  qKvar: number;

  /**
   * storage only
   *
   * @generated from field: double soc_fraction = 5;
   */
  socFraction: number;
};

/**
 * Describes the message metacore.module1.v1.NodeState.
 * Use `create(NodeStateSchema)` to create a new message.
 */
export declare const NodeStateSchema: GenMessage<NodeState>;

/**
 * ---------------------------------------------------------------- M1 -> M3
 * Secondary input to the Meta-RL gate state, alongside M2's uncertainty scalar.
 *
 * @generated from message metacore.module1.v1.SystemContext
 */
export declare type SystemContext = Message<"metacore.module1.v1.SystemContext"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * 0..1
   *
   * @generated from field: float max_node_vulnerability = 2;
   */
  maxNodeVulnerability: number;

  /**
   * @generated from field: float mean_node_vulnerability = 3;
   */
  meanNodeVulnerability: number;

  /**
   * @generated from field: repeated string top_at_risk_nodes = 4;
   */
  topAtRiskNodes: string[];

  /**
   * negative once the hazard has arrived
   *
   * @generated from field: float time_to_hazard_onset_min = 5;
   */
  timeToHazardOnsetMin: number;

  /**
   * @generated from field: metacore.module1.v1.HazardSeverity severity = 6;
   */
  severity: HazardSeverity;
};

/**
 * Describes the message metacore.module1.v1.SystemContext.
 * Use `create(SystemContextSchema)` to create a new message.
 */
export declare const SystemContextSchema: GenMessage<SystemContext>;

/**
 * Per-node forecast for the dashboard map view.
 *
 * @generated from message metacore.module1.v1.VulnerabilityForecast
 */
export declare type VulnerabilityForecast = Message<"metacore.module1.v1.VulnerabilityForecast"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: uint32 horizon_steps = 2;
   */
  horizonSteps: number;

  /**
   * @generated from field: repeated metacore.module1.v1.NodeVulnerability nodes = 3;
   */
  nodes: NodeVulnerability[];
};

/**
 * Describes the message metacore.module1.v1.VulnerabilityForecast.
 * Use `create(VulnerabilityForecastSchema)` to create a new message.
 */
export declare const VulnerabilityForecastSchema: GenMessage<VulnerabilityForecast>;

/**
 * @generated from message metacore.module1.v1.NodeVulnerability
 */
export declare type NodeVulnerability = Message<"metacore.module1.v1.NodeVulnerability"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * 0..1, t+1 .. t+horizon_steps
   *
   * @generated from field: repeated float score_per_horizon = 2;
   */
  scorePerHorizon: number[];
};

/**
 * Describes the message metacore.module1.v1.NodeVulnerability.
 * Use `create(NodeVulnerabilitySchema)` to create a new message.
 */
export declare const NodeVulnerabilitySchema: GenMessage<NodeVulnerability>;

/**
 * @generated from message metacore.module1.v1.TopologyRequest
 */
export declare type TopologyRequest = Message<"metacore.module1.v1.TopologyRequest"> & {
  /**
   * @generated from field: string topology_id = 1;
   */
  topologyId: string;
};

/**
 * Describes the message metacore.module1.v1.TopologyRequest.
 * Use `create(TopologyRequestSchema)` to create a new message.
 */
export declare const TopologyRequestSchema: GenMessage<TopologyRequest>;

/**
 * @generated from message metacore.module1.v1.StateRequest
 */
export declare type StateRequest = Message<"metacore.module1.v1.StateRequest"> & {
  /**
   * @generated from field: metacore.common.v1.ScenarioRef scenario = 1;
   */
  scenario?: ScenarioRef | undefined;
};

/**
 * Describes the message metacore.module1.v1.StateRequest.
 * Use `create(StateRequestSchema)` to create a new message.
 */
export declare const StateRequestSchema: GenMessage<StateRequest>;

/**
 * @generated from message metacore.module1.v1.HealthRequest
 */
export declare type HealthRequest = Message<"metacore.module1.v1.HealthRequest"> & {
};

/**
 * Describes the message metacore.module1.v1.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export declare const HealthRequestSchema: GenMessage<HealthRequest>;

/**
 * @generated from enum metacore.module1.v1.AssetType
 */
export enum AssetType {
  /**
   * @generated from enum value: ASSET_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ASSET_TYPE_BUS = 1;
   */
  BUS = 1,

  /**
   * @generated from enum value: ASSET_TYPE_PV = 2;
   */
  PV = 2,

  /**
   * @generated from enum value: ASSET_TYPE_WIND = 3;
   */
  WIND = 3,

  /**
   * @generated from enum value: ASSET_TYPE_BESS = 4;
   */
  BESS = 4,

  /**
   * @generated from enum value: ASSET_TYPE_DIESEL = 5;
   */
  DIESEL = 5,

  /**
   * @generated from enum value: ASSET_TYPE_LOAD = 6;
   */
  LOAD = 6,
}

/**
 * Describes the enum metacore.module1.v1.AssetType.
 */
export declare const AssetTypeSchema: GenEnum<AssetType>;

/**
 * @generated from enum metacore.module1.v1.HazardSeverity
 */
export enum HazardSeverity {
  /**
   * @generated from enum value: HAZARD_SEVERITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: HAZARD_SEVERITY_NORMAL = 1;
   */
  NORMAL = 1,

  /**
   * @generated from enum value: HAZARD_SEVERITY_ELEVATED = 2;
   */
  ELEVATED = 2,

  /**
   * @generated from enum value: HAZARD_SEVERITY_SEVERE = 3;
   */
  SEVERE = 3,

  /**
   * @generated from enum value: HAZARD_SEVERITY_EXTREME = 4;
   */
  EXTREME = 4,
}

/**
 * Describes the enum metacore.module1.v1.HazardSeverity.
 */
export declare const HazardSeveritySchema: GenEnum<HazardSeverity>;

/**
 * @generated from service metacore.module1.v1.StateRepresentationService
 */
export declare const StateRepresentationService: GenService<{
  /**
   * @generated from rpc metacore.module1.v1.StateRepresentationService.GetTopology
   */
  getTopology: {
    methodKind: "unary";
    input: typeof TopologyRequestSchema;
    output: typeof GridTopologySchema;
  },
  /**
   * @generated from rpc metacore.module1.v1.StateRepresentationService.StreamState
   */
  streamState: {
    methodKind: "server_streaming";
    input: typeof StateRequestSchema;
    output: typeof StateRepresentationSchema;
  },
  /**
   * @generated from rpc metacore.module1.v1.StateRepresentationService.StreamSnapshot
   */
  streamSnapshot: {
    methodKind: "server_streaming";
    input: typeof StateRequestSchema;
    output: typeof GridStateSnapshotSchema;
  },
  /**
   * @generated from rpc metacore.module1.v1.StateRepresentationService.StreamContext
   */
  streamContext: {
    methodKind: "server_streaming";
    input: typeof StateRequestSchema;
    output: typeof SystemContextSchema;
  },
  /**
   * @generated from rpc metacore.module1.v1.StateRepresentationService.Health
   */
  health: {
    methodKind: "unary";
    input: typeof HealthRequestSchema;
    output: typeof HealthSchema;
  },
}>;

