// @generated by protoc-gen-es v2.14.0
// @generated from file module2.proto (package metacore.module2.v1, syntax proto3)
/* eslint-disable */

// Module 2 — Agentic Epistemic Uncertainty Quantification.
// Owner: Duwaragie K. (IT23270442). Consumer: M3.

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "./common_pb";

/**
 * Describes the file module2.proto.
 */
export const file_module2 = /*@__PURE__*/
  fileDesc("Cg1tb2R1bGUyLnByb3RvEhNtZXRhY29yZS5tb2R1bGUyLnYxIuABChNVbmNlcnRhaW50eUVzdGltYXRlEi4KCGVudmVsb3BlGAEgASgLMhwubWV0YWNvcmUuY29tbW9uLnYxLkVudmVsb3BlEhEKCWtfY2xhc3NlcxgCIAEoDRIQCghldmlkZW5jZRgDIAMoAhIWCg50b3RhbF9ldmlkZW5jZRgEIAEoAhIRCgllcGlzdGVtaWMYBSABKAISEQoJYWxlYXRvcmljGAYgASgCEhkKEWNsYXNzX3Byb2JhYmlsaXR5GAcgAygCEhsKE2ZhaWxfc2FmZV90cmlnZ2VyZWQYCCABKAgisQEKFUNvbXBldGVuY2VEcm9wVHJpZ2dlchIuCghlbnZlbG9wZRgBIAEoCzIcLm1ldGFjb3JlLmNvbW1vbi52MS5FbnZlbG9wZRIOCgZhY3RpdmUYAiABKAgSEQoJZXBpc3RlbWljGAMgASgCEhEKCXRocmVzaG9sZBgEIAEoAhIXCg9oeXN0ZXJlc2lzX2JhbmQYBSABKAISGQoRY29uc2VjdXRpdmVfc3RlcHMYBiABKAQiRwoSVW5jZXJ0YWludHlSZXF1ZXN0EjEKCHNjZW5hcmlvGAEgASgLMh8ubWV0YWNvcmUuY29tbW9uLnYxLlNjZW5hcmlvUmVmIg8KDUhlYWx0aFJlcXVlc3QysAIKElVuY2VydGFpbnR5U2VydmljZRJoChFTdHJlYW1VbmNlcnRhaW50eRInLm1ldGFjb3JlLm1vZHVsZTIudjEuVW5jZXJ0YWludHlSZXF1ZXN0GigubWV0YWNvcmUubW9kdWxlMi52MS5VbmNlcnRhaW50eUVzdGltYXRlMAESZgoNU3RyZWFtVHJpZ2dlchInLm1ldGFjb3JlLm1vZHVsZTIudjEuVW5jZXJ0YWludHlSZXF1ZXN0GioubWV0YWNvcmUubW9kdWxlMi52MS5Db21wZXRlbmNlRHJvcFRyaWdnZXIwARJICgZIZWFsdGgSIi5tZXRhY29yZS5tb2R1bGUyLnYxLkhlYWx0aFJlcXVlc3QaGi5tZXRhY29yZS5jb21tb24udjEuSGVhbHRoQswBChdjb20ubWV0YWNvcmUubW9kdWxlMi52MUIMTW9kdWxlMlByb3RvUAFaNWdpdGh1Yi5jb20vbWV0YWNvcmUvY29udHJhY3RzL2dvL21vZHVsZTIvdjE7bW9kdWxlMnYxogIDTU1YqgITTWV0YWNvcmUuTW9kdWxlMi5WMcoCE01ldGFjb3JlXE1vZHVsZTJcVjHiAh9NZXRhY29yZVxNb2R1bGUyXFYxXEdQQk1ldGFkYXRh6gIVTWV0YWNvcmU6Ok1vZHVsZTI6OlYxYgZwcm90bzM", [file_common]);

/**
 * Describes the message metacore.module2.v1.UncertaintyEstimate.
 * Use `create(UncertaintyEstimateSchema)` to create a new message.
 */
export const UncertaintyEstimateSchema = /*@__PURE__*/
  messageDesc(file_module2, 0);

/**
 * Describes the message metacore.module2.v1.CompetenceDropTrigger.
 * Use `create(CompetenceDropTriggerSchema)` to create a new message.
 */
export const CompetenceDropTriggerSchema = /*@__PURE__*/
  messageDesc(file_module2, 1);

/**
 * Describes the message metacore.module2.v1.UncertaintyRequest.
 * Use `create(UncertaintyRequestSchema)` to create a new message.
 */
export const UncertaintyRequestSchema = /*@__PURE__*/
  messageDesc(file_module2, 2);

/**
 * Describes the message metacore.module2.v1.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export const HealthRequestSchema = /*@__PURE__*/
  messageDesc(file_module2, 3);

/**
 * @generated from service metacore.module2.v1.UncertaintyService
 */
export const UncertaintyService = /*@__PURE__*/
  serviceDesc(file_module2, 0);

