// @generated by protoc-gen-es v2.14.0
// @generated from file module2.proto (package metacore.module2.v1, syntax proto3)
/* eslint-disable */

// Module 2 — Agentic Epistemic Uncertainty Quantification.
// Owner: Duwaragie K. (IT23270442). Consumer: M3.

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Envelope, HealthSchema, ScenarioRef } from "./common_pb";

/**
 * Describes the file module2.proto.
 */
export declare const file_module2: GenFile;

/**
 * Dirichlet evidence over K grid-safety state classes, with the epistemic/aleatoric split.
 *
 * @generated from message metacore.module2.v1.UncertaintyEstimate
 */
export declare type UncertaintyEstimate = Message<"metacore.module2.v1.UncertaintyEstimate"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: uint32 k_classes = 2;
   */
  kClasses: number;

  /**
   * per-class Dirichlet evidence
   *
   * @generated from field: repeated float evidence = 3;
   */
  evidence: number[];

  /**
   * S
   *
   * @generated from field: float total_evidence = 4;
   */
  totalEvidence: number;

  /**
   * u = K / S, in [0, 1]
   *
   * @generated from field: float epistemic = 5;
   */
  epistemic: number;

  /**
   * @generated from field: float aleatoric = 6;
   */
  aleatoric: number;

  /**
   * @generated from field: repeated float class_probability = 7;
   */
  classProbability: number[];

  /**
   * Set when the input state carried missing modalities. Fail-safe: a malformed or absent input
   * must produce high epistemic uncertainty, never a confident signal.
   *
   * @generated from field: bool fail_safe_triggered = 8;
   */
  failSafeTriggered: boolean;
};

/**
 * Describes the message metacore.module2.v1.UncertaintyEstimate.
 * Use `create(UncertaintyEstimateSchema)` to create a new message.
 */
export declare const UncertaintyEstimateSchema: GenMessage<UncertaintyEstimate>;

/**
 * Discrete trigger with hysteresis so the gate does not chatter around the threshold.
 *
 * @generated from message metacore.module2.v1.CompetenceDropTrigger
 */
export declare type CompetenceDropTrigger = Message<"metacore.module2.v1.CompetenceDropTrigger"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: bool active = 2;
   */
  active: boolean;

  /**
   * @generated from field: float epistemic = 3;
   */
  epistemic: number;

  /**
   * @generated from field: float threshold = 4;
   */
  threshold: number;

  /**
   * @generated from field: float hysteresis_band = 5;
   */
  hysteresisBand: number;

  /**
   * @generated from field: uint64 consecutive_steps = 6;
   */
  consecutiveSteps: bigint;
};

/**
 * Describes the message metacore.module2.v1.CompetenceDropTrigger.
 * Use `create(CompetenceDropTriggerSchema)` to create a new message.
 */
export declare const CompetenceDropTriggerSchema: GenMessage<CompetenceDropTrigger>;

/**
 * @generated from message metacore.module2.v1.UncertaintyRequest
 */
export declare type UncertaintyRequest = Message<"metacore.module2.v1.UncertaintyRequest"> & {
  /**
   * @generated from field: metacore.common.v1.ScenarioRef scenario = 1;
   */
  scenario?: ScenarioRef | undefined;
};

/**
 * Describes the message metacore.module2.v1.UncertaintyRequest.
 * Use `create(UncertaintyRequestSchema)` to create a new message.
 */
export declare const UncertaintyRequestSchema: GenMessage<UncertaintyRequest>;

/**
 * @generated from message metacore.module2.v1.HealthRequest
 */
export declare type HealthRequest = Message<"metacore.module2.v1.HealthRequest"> & {
};

/**
 * Describes the message metacore.module2.v1.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export declare const HealthRequestSchema: GenMessage<HealthRequest>;

/**
 * @generated from service metacore.module2.v1.UncertaintyService
 */
export declare const UncertaintyService: GenService<{
  /**
   * @generated from rpc metacore.module2.v1.UncertaintyService.StreamUncertainty
   */
  streamUncertainty: {
    methodKind: "server_streaming";
    input: typeof UncertaintyRequestSchema;
    output: typeof UncertaintyEstimateSchema;
  },
  /**
   * @generated from rpc metacore.module2.v1.UncertaintyService.StreamTrigger
   */
  streamTrigger: {
    methodKind: "server_streaming";
    input: typeof UncertaintyRequestSchema;
    output: typeof CompetenceDropTriggerSchema;
  },
  /**
   * @generated from rpc metacore.module2.v1.UncertaintyService.Health
   */
  health: {
    methodKind: "unary";
    input: typeof HealthRequestSchema;
    output: typeof HealthSchema;
  },
}>;

