// @generated by protoc-gen-es v2.14.0
// @generated from file verification.proto (package metacore.verification.v1, syntax proto3)
/* eslint-disable */

// Module 4 — Abductive Physics-Informed Verification & Semantic Translation.
// Owner: Hariswara S. (IT23291782). Consumers: M3 (verdict), M2 (rejection trace), dashboard.
//
// DETERMINISTIC. The verdict is produced by an OpenDSS power-flow solve against a safety
// specification. Nothing in the decision path is learned.

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Envelope, HealthSchema, ScenarioRef } from "./common_pb";
import type { ProposedControlAction } from "./module3_pb";

/**
 * Describes the file verification.proto.
 */
export declare const file_verification: GenFile;

/**
 * @generated from message metacore.verification.v1.VerificationRequest
 */
export declare type VerificationRequest = Message<"metacore.verification.v1.VerificationRequest"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: metacore.module3.v1.ProposedControlAction action = 2;
   */
  action?: ProposedControlAction | undefined;

  /**
   * @generated from field: string topology_id = 3;
   */
  topologyId: string;
};

/**
 * Describes the message metacore.verification.v1.VerificationRequest.
 * Use `create(VerificationRequestSchema)` to create a new message.
 */
export declare const VerificationRequestSchema: GenMessage<VerificationRequest>;

/**
 * @generated from message metacore.verification.v1.VerificationVerdict
 */
export declare type VerificationVerdict = Message<"metacore.verification.v1.VerificationVerdict"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: string action_id = 2;
   */
  actionId: string;

  /**
   * @generated from field: metacore.verification.v1.Decision decision = 3;
   */
  decision: Decision;

  /**
   * empty on APPROVE
   *
   * @generated from field: repeated metacore.verification.v1.Violation violations = 4;
   */
  violations: Violation[];

  /**
   * @generated from field: double solve_latency_ms = 5;
   */
  solveLatencyMs: number;

  /**
   * the safety specification this was judged against
   *
   * @generated from field: string spec_version = 6;
   */
  specVersion: string;

  /**
   * @generated from field: string network_model_version = 7;
   */
  networkModelVersion: string;
};

/**
 * Describes the message metacore.verification.v1.VerificationVerdict.
 * Use `create(VerificationVerdictSchema)` to create a new message.
 */
export declare const VerificationVerdictSchema: GenMessage<VerificationVerdict>;

/**
 * Structured violation evidence — the analytical core of the abductive claim, and the payload
 * the causal log is generated from. A generated explanation may only reference entities present
 * here; anything else is an ungrounded claim.
 *
 * @generated from message metacore.verification.v1.Violation
 */
export declare type Violation = Message<"metacore.verification.v1.Violation"> & {
  /**
   * @generated from field: metacore.verification.v1.ViolationType type = 1;
   */
  type: ViolationType;

  /**
   * offending bus or line
   *
   * @generated from field: string element_id = 2;
   */
  elementId: string;

  /**
   * @generated from field: double measured = 3;
   */
  measured: number;

  /**
   * @generated from field: double limit = 4;
   */
  limit: number;

  /**
   * signed: how far past the limit
   *
   * @generated from field: double margin_fraction = 5;
   */
  marginFraction: number;

  /**
   * Which part of the proposed action most plausibly caused this (attribution, not certainty).
   *
   * @generated from field: string attributed_component = 6;
   */
  attributedComponent: string;
};

/**
 * Describes the message metacore.verification.v1.Violation.
 * Use `create(ViolationSchema)` to create a new message.
 */
export declare const ViolationSchema: GenMessage<Violation>;

/**
 * M4 -> M2. Feeds back into the competence signal so a rejection informs future uncertainty.
 *
 * @generated from message metacore.verification.v1.RejectionTrace
 */
export declare type RejectionTrace = Message<"metacore.verification.v1.RejectionTrace"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: string action_id = 2;
   */
  actionId: string;

  /**
   * @generated from field: repeated metacore.verification.v1.Violation violations = 3;
   */
  violations: Violation[];

  /**
   * 0..1, derived from margin_fraction across violations
   *
   * @generated from field: float severity = 4;
   */
  severity: number;
};

/**
 * Describes the message metacore.verification.v1.RejectionTrace.
 * Use `create(RejectionTraceSchema)` to create a new message.
 */
export declare const RejectionTraceSchema: GenMessage<RejectionTrace>;

/**
 * M4 -> operator dashboard. Grounded in the structured evidence above.
 *
 * @generated from message metacore.verification.v1.CausalLog
 */
export declare type CausalLog = Message<"metacore.verification.v1.CausalLog"> & {
  /**
   * @generated from field: metacore.common.v1.Envelope envelope = 1;
   */
  envelope?: Envelope | undefined;

  /**
   * @generated from field: string action_id = 2;
   */
  actionId: string;

  /**
   * @generated from field: string text = 3;
   */
  text: string;

  /**
   * must be a subset of the violation element_ids
   *
   * @generated from field: repeated string grounded_entities = 4;
   */
  groundedEntities: string[];

  /**
   * @generated from field: metacore.verification.v1.Generator generator = 5;
   */
  generator: Generator;
};

/**
 * Describes the message metacore.verification.v1.CausalLog.
 * Use `create(CausalLogSchema)` to create a new message.
 */
export declare const CausalLogSchema: GenMessage<CausalLog>;

/**
 * @generated from message metacore.verification.v1.RejectionRequest
 */
export declare type RejectionRequest = Message<"metacore.verification.v1.RejectionRequest"> & {
  /**
   * @generated from field: metacore.common.v1.ScenarioRef scenario = 1;
   */
  scenario?: ScenarioRef | undefined;
};

/**
 * Describes the message metacore.verification.v1.RejectionRequest.
 * Use `create(RejectionRequestSchema)` to create a new message.
 */
export declare const RejectionRequestSchema: GenMessage<RejectionRequest>;

/**
 * @generated from message metacore.verification.v1.HealthRequest
 */
export declare type HealthRequest = Message<"metacore.verification.v1.HealthRequest"> & {
};

/**
 * Describes the message metacore.verification.v1.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export declare const HealthRequestSchema: GenMessage<HealthRequest>;

/**
 * @generated from enum metacore.verification.v1.Decision
 */
export enum Decision {
  /**
   * @generated from enum value: DECISION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DECISION_APPROVE = 1;
   */
  APPROVE = 1,

  /**
   * @generated from enum value: DECISION_REJECT = 2;
   */
  REJECT = 2,
}

/**
 * Describes the enum metacore.verification.v1.Decision.
 */
export declare const DecisionSchema: GenEnum<Decision>;

/**
 * @generated from enum metacore.verification.v1.ViolationType
 */
export enum ViolationType {
  /**
   * @generated from enum value: VIOLATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: VIOLATION_TYPE_UNDERVOLTAGE = 1;
   */
  UNDERVOLTAGE = 1,

  /**
   * @generated from enum value: VIOLATION_TYPE_OVERVOLTAGE = 2;
   */
  OVERVOLTAGE = 2,

  /**
   * @generated from enum value: VIOLATION_TYPE_THERMAL_OVERLOAD = 3;
   */
  THERMAL_OVERLOAD = 3,

  /**
   * @generated from enum value: VIOLATION_TYPE_NON_CONVERGENCE = 4;
   */
  NON_CONVERGENCE = 4,

  /**
   * @generated from enum value: VIOLATION_TYPE_MALFORMED_ACTION = 5;
   */
  MALFORMED_ACTION = 5,
}

/**
 * Describes the enum metacore.verification.v1.ViolationType.
 */
export declare const ViolationTypeSchema: GenEnum<ViolationType>;

/**
 * @generated from enum metacore.verification.v1.Generator
 */
export enum Generator {
  /**
   * @generated from enum value: GENERATOR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * deterministic, the default
   *
   * @generated from enum value: GENERATOR_TEMPLATE = 1;
   */
  TEMPLATE = 1,

  /**
   * learned but grounding-checked; never part of the decision
   *
   * @generated from enum value: GENERATOR_CONSTRAINED = 2;
   */
  CONSTRAINED = 2,
}

/**
 * Describes the enum metacore.verification.v1.Generator.
 */
export declare const GeneratorSchema: GenEnum<Generator>;

/**
 * @generated from service metacore.verification.v1.VerificationService
 */
export declare const VerificationService: GenService<{
  /**
   * Blocking. The orchestrator waits on this; the firewall is not bypassable.
   *
   * @generated from rpc metacore.verification.v1.VerificationService.Verify
   */
  verify: {
    methodKind: "unary";
    input: typeof VerificationRequestSchema;
    output: typeof VerificationVerdictSchema;
  },
  /**
   * @generated from rpc metacore.verification.v1.VerificationService.StreamRejections
   */
  streamRejections: {
    methodKind: "server_streaming";
    input: typeof RejectionRequestSchema;
    output: typeof RejectionTraceSchema;
  },
  /**
   * @generated from rpc metacore.verification.v1.VerificationService.StreamCausalLogs
   */
  streamCausalLogs: {
    methodKind: "server_streaming";
    input: typeof RejectionRequestSchema;
    output: typeof CausalLogSchema;
  },
  /**
   * @generated from rpc metacore.verification.v1.VerificationService.Health
   */
  health: {
    methodKind: "unary";
    input: typeof HealthRequestSchema;
    output: typeof HealthSchema;
  },
}>;

