# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x12metacore.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n\rSchemaVersion\x12\x14\n\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n\x05minor\x18\x02 \x01(\rR\x05minor\"x\n\x0bQualityMask\x12<\n\x0bper_feature\x18\x01 \x03(\x0e\x32\x1b.metacore.common.v1.QualityR\nperFeature\x12+\n\x11observed_fraction\x18\x02 \x01(\x02R\x10observedFraction\"\x87\x01\n\x0bScenarioRef\x12\x1f\n\x0bscenario_id\x18\x01 \x01(\tR\nscenarioId\x12\'\n\x0flibrary_version\x18\x02 \x01(\tR\x0elibraryVersion\x12.\n\x13out_of_distribution\x18\x03 \x01(\x08R\x11outOfDistribution\"\x83\x02\n\x08\x45nvelope\x12H\n\x0eschema_version\x18\x01 \x01(\x0b\x32!.metacore.common.v1.SchemaVersionR\rschemaVersion\x12\x39\n\nemitted_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\temittedAt\x12\x1a\n\x08producer\x18\x03 \x01(\tR\x08producer\x12;\n\x08scenario\x18\x04 \x01(\x0b\x32\x1f.metacore.common.v1.ScenarioRefR\x08scenario\x12\x19\n\x08trace_id\x18\x05 \x01(\tR\x07traceId\"g\n\x06Health\x12\x14\n\x05ready\x18\x01 \x01(\x08R\x05ready\x12\x16\n\x06\x64\x65tail\x18\x02 \x01(\tR\x06\x64\x65tail\x12/\n\x14last_step_latency_ms\x18\x03 \x01(\x01R\x11lastStepLatencyMs*z\n\x07Quality\x12\x17\n\x13QUALITY_UNSPECIFIED\x10\x00\x12\x14\n\x10QUALITY_OBSERVED\x10\x01\x12\x18\n\x14QUALITY_INTERPOLATED\x10\x02\x12\x13\n\x0fQUALITY_MISSING\x10\x03\x12\x11\n\rQUALITY_STALE\x10\x04\x42\xc4\x01\n\x16\x63om.metacore.common.v1B\x0b\x43ommonProtoP\x01Z3github.com/metacore/contracts/go/common/v1;commonv1\xa2\x02\x03MCX\xaa\x02\x12Metacore.Common.V1\xca\x02\x12Metacore\\Common\\V1\xe2\x02\x1eMetacore\\Common\\V1\\GPBMetadata\xea\x02\x14Metacore::Common::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.metacore.common.v1B\013CommonProtoP\001Z3github.com/metacore/contracts/go/common/v1;commonv1\242\002\003MCX\252\002\022Metacore.Common.V1\312\002\022Metacore\\Common\\V1\342\002\036Metacore\\Common\\V1\\GPBMetadata\352\002\024Metacore::Common::V1'
  _globals['_QUALITY']._serialized_start=757
  _globals['_QUALITY']._serialized_end=879
  _globals['_SCHEMAVERSION']._serialized_start=69
  _globals['_SCHEMAVERSION']._serialized_end=128
  _globals['_QUALITYMASK']._serialized_start=130
  _globals['_QUALITYMASK']._serialized_end=250
  _globals['_SCENARIOREF']._serialized_start=253
  _globals['_SCENARIOREF']._serialized_end=388
  _globals['_ENVELOPE']._serialized_start=391
  _globals['_ENVELOPE']._serialized_end=650
  _globals['_HEALTH']._serialized_start=652
  _globals['_HEALTH']._serialized_end=755
# @@protoc_insertion_point(module_scope)
