# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import module2_pb2 as module2__pb2


class UncertaintyServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamUncertainty = channel.unary_stream(
                '/metacore.module2.v1.UncertaintyService/StreamUncertainty',
                request_serializer=module2__pb2.UncertaintyRequest.SerializeToString,
                response_deserializer=module2__pb2.UncertaintyEstimate.FromString,
                _registered_method=True)
        self.StreamTrigger = channel.unary_stream(
                '/metacore.module2.v1.UncertaintyService/StreamTrigger',
                request_serializer=module2__pb2.UncertaintyRequest.SerializeToString,
                response_deserializer=module2__pb2.CompetenceDropTrigger.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/metacore.module2.v1.UncertaintyService/Health',
                request_serializer=module2__pb2.HealthRequest.SerializeToString,
                response_deserializer=common__pb2.Health.FromString,
                _registered_method=True)


class UncertaintyServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamUncertainty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UncertaintyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamUncertainty': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUncertainty,
                    request_deserializer=module2__pb2.UncertaintyRequest.FromString,
                    response_serializer=module2__pb2.UncertaintyEstimate.SerializeToString,
            ),
            'StreamTrigger': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrigger,
                    request_deserializer=module2__pb2.UncertaintyRequest.FromString,
                    response_serializer=module2__pb2.CompetenceDropTrigger.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=module2__pb2.HealthRequest.FromString,
                    response_serializer=common__pb2.Health.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metacore.module2.v1.UncertaintyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metacore.module2.v1.UncertaintyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UncertaintyService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamUncertainty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.module2.v1.UncertaintyService/StreamUncertainty',
            module2__pb2.UncertaintyRequest.SerializeToString,
            module2__pb2.UncertaintyEstimate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.module2.v1.UncertaintyService/StreamTrigger',
            module2__pb2.UncertaintyRequest.SerializeToString,
            module2__pb2.CompetenceDropTrigger.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metacore.module2.v1.UncertaintyService/Health',
            module2__pb2.HealthRequest.SerializeToString,
            common__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
