# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import module3_pb2 as module3__pb2


class GatingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAction = channel.unary_stream(
                '/metacore.module3.v1.GatingService/StreamAction',
                request_serializer=module3__pb2.GatingRequest.SerializeToString,
                response_deserializer=module3__pb2.ProposedControlAction.FromString,
                _registered_method=True)
        self.StreamDecision = channel.unary_stream(
                '/metacore.module3.v1.GatingService/StreamDecision',
                request_serializer=module3__pb2.GatingRequest.SerializeToString,
                response_deserializer=module3__pb2.GatingDecision.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/metacore.module3.v1.GatingService/Health',
                request_serializer=module3__pb2.HealthRequest.SerializeToString,
                response_deserializer=common__pb2.Health.FromString,
                _registered_method=True)


class GatingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAction': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAction,
                    request_deserializer=module3__pb2.GatingRequest.FromString,
                    response_serializer=module3__pb2.ProposedControlAction.SerializeToString,
            ),
            'StreamDecision': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDecision,
                    request_deserializer=module3__pb2.GatingRequest.FromString,
                    response_serializer=module3__pb2.GatingDecision.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=module3__pb2.HealthRequest.FromString,
                    response_serializer=common__pb2.Health.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metacore.module3.v1.GatingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metacore.module3.v1.GatingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.module3.v1.GatingService/StreamAction',
            module3__pb2.GatingRequest.SerializeToString,
            module3__pb2.ProposedControlAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.module3.v1.GatingService/StreamDecision',
            module3__pb2.GatingRequest.SerializeToString,
            module3__pb2.GatingDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metacore.module3.v1.GatingService/Health',
            module3__pb2.HealthRequest.SerializeToString,
            common__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
