# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import common_pb2 as common__pb2
from . import module1_pb2 as module1__pb2


class StateRepresentationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTopology = channel.unary_unary(
                '/metacore.module1.v1.StateRepresentationService/GetTopology',
                request_serializer=module1__pb2.TopologyRequest.SerializeToString,
                response_deserializer=module1__pb2.GridTopology.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/metacore.module1.v1.StateRepresentationService/StreamState',
                request_serializer=module1__pb2.StateRequest.SerializeToString,
                response_deserializer=module1__pb2.StateRepresentation.FromString,
                _registered_method=True)
        self.StreamSnapshot = channel.unary_stream(
                '/metacore.module1.v1.StateRepresentationService/StreamSnapshot',
                request_serializer=module1__pb2.StateRequest.SerializeToString,
                response_deserializer=module1__pb2.GridStateSnapshot.FromString,
                _registered_method=True)
        self.StreamContext = channel.unary_stream(
                '/metacore.module1.v1.StateRepresentationService/StreamContext',
                request_serializer=module1__pb2.StateRequest.SerializeToString,
                response_deserializer=module1__pb2.SystemContext.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/metacore.module1.v1.StateRepresentationService/Health',
                request_serializer=module1__pb2.HealthRequest.SerializeToString,
                response_deserializer=common__pb2.Health.FromString,
                _registered_method=True)


class StateRepresentationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetTopology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateRepresentationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=module1__pb2.TopologyRequest.FromString,
                    response_serializer=module1__pb2.GridTopology.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=module1__pb2.StateRequest.FromString,
                    response_serializer=module1__pb2.StateRepresentation.SerializeToString,
            ),
            'StreamSnapshot': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSnapshot,
                    request_deserializer=module1__pb2.StateRequest.FromString,
                    response_serializer=module1__pb2.GridStateSnapshot.SerializeToString,
            ),
            'StreamContext': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamContext,
                    request_deserializer=module1__pb2.StateRequest.FromString,
                    response_serializer=module1__pb2.SystemContext.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=module1__pb2.HealthRequest.FromString,
                    response_serializer=common__pb2.Health.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metacore.module1.v1.StateRepresentationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metacore.module1.v1.StateRepresentationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateRepresentationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metacore.module1.v1.StateRepresentationService/GetTopology',
            module1__pb2.TopologyRequest.SerializeToString,
            module1__pb2.GridTopology.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.module1.v1.StateRepresentationService/StreamState',
            module1__pb2.StateRequest.SerializeToString,
            module1__pb2.StateRepresentation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.module1.v1.StateRepresentationService/StreamSnapshot',
            module1__pb2.StateRequest.SerializeToString,
            module1__pb2.GridStateSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.module1.v1.StateRepresentationService/StreamContext',
            module1__pb2.StateRequest.SerializeToString,
            module1__pb2.SystemContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metacore.module1.v1.StateRepresentationService/Health',
            module1__pb2.HealthRequest.SerializeToString,
            common__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
