# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: module2.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'module2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmodule2.proto\x12\x13metacore.module2.v1\x1a\x0c\x63ommon.proto\"\xc8\x02\n\x13UncertaintyEstimate\x12\x38\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32\x1c.metacore.common.v1.EnvelopeR\x08\x65nvelope\x12\x1b\n\tk_classes\x18\x02 \x01(\rR\x08kClasses\x12\x1a\n\x08\x65vidence\x18\x03 \x03(\x02R\x08\x65vidence\x12%\n\x0etotal_evidence\x18\x04 \x01(\x02R\rtotalEvidence\x12\x1c\n\tepistemic\x18\x05 \x01(\x02R\tepistemic\x12\x1c\n\taleatoric\x18\x06 \x01(\x02R\taleatoric\x12+\n\x11\x63lass_probability\x18\x07 \x03(\x02R\x10\x63lassProbability\x12.\n\x13\x66\x61il_safe_triggered\x18\x08 \x01(\x08R\x11\x66\x61ilSafeTriggered\"\xfb\x01\n\x15\x43ompetenceDropTrigger\x12\x38\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32\x1c.metacore.common.v1.EnvelopeR\x08\x65nvelope\x12\x16\n\x06\x61\x63tive\x18\x02 \x01(\x08R\x06\x61\x63tive\x12\x1c\n\tepistemic\x18\x03 \x01(\x02R\tepistemic\x12\x1c\n\tthreshold\x18\x04 \x01(\x02R\tthreshold\x12\'\n\x0fhysteresis_band\x18\x05 \x01(\x02R\x0ehysteresisBand\x12+\n\x11\x63onsecutive_steps\x18\x06 \x01(\x04R\x10\x63onsecutiveSteps\"Q\n\x12UncertaintyRequest\x12;\n\x08scenario\x18\x01 \x01(\x0b\x32\x1f.metacore.common.v1.ScenarioRefR\x08scenario\"\x0f\n\rHealthRequest2\xb0\x02\n\x12UncertaintyService\x12h\n\x11StreamUncertainty\x12\'.metacore.module2.v1.UncertaintyRequest\x1a(.metacore.module2.v1.UncertaintyEstimate0\x01\x12\x66\n\rStreamTrigger\x12\'.metacore.module2.v1.UncertaintyRequest\x1a*.metacore.module2.v1.CompetenceDropTrigger0\x01\x12H\n\x06Health\x12\".metacore.module2.v1.HealthRequest\x1a\x1a.metacore.common.v1.HealthB\xcc\x01\n\x17\x63om.metacore.module2.v1B\x0cModule2ProtoP\x01Z5github.com/metacore/contracts/go/module2/v1;module2v1\xa2\x02\x03MMX\xaa\x02\x13Metacore.Module2.V1\xca\x02\x13Metacore\\Module2\\V1\xe2\x02\x1fMetacore\\Module2\\V1\\GPBMetadata\xea\x02\x15Metacore::Module2::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'module2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.metacore.module2.v1B\014Module2ProtoP\001Z5github.com/metacore/contracts/go/module2/v1;module2v1\242\002\003MMX\252\002\023Metacore.Module2.V1\312\002\023Metacore\\Module2\\V1\342\002\037Metacore\\Module2\\V1\\GPBMetadata\352\002\025Metacore::Module2::V1'
  _globals['_UNCERTAINTYESTIMATE']._serialized_start=53
  _globals['_UNCERTAINTYESTIMATE']._serialized_end=381
  _globals['_COMPETENCEDROPTRIGGER']._serialized_start=384
  _globals['_COMPETENCEDROPTRIGGER']._serialized_end=635
  _globals['_UNCERTAINTYREQUEST']._serialized_start=637
  _globals['_UNCERTAINTYREQUEST']._serialized_end=718
  _globals['_HEALTHREQUEST']._serialized_start=720
  _globals['_HEALTHREQUEST']._serialized_end=735
  _globals['_UNCERTAINTYSERVICE']._serialized_start=738
  _globals['_UNCERTAINTYSERVICE']._serialized_end=1042
# @@protoc_insertion_point(module_scope)
