# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import common_pb2 as common__pb2
from . import verification_pb2 as verification__pb2


class VerificationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Verify = channel.unary_unary(
                '/metacore.verification.v1.VerificationService/Verify',
                request_serializer=verification__pb2.VerificationRequest.SerializeToString,
                response_deserializer=verification__pb2.VerificationVerdict.FromString,
                _registered_method=True)
        self.StreamRejections = channel.unary_stream(
                '/metacore.verification.v1.VerificationService/StreamRejections',
                request_serializer=verification__pb2.RejectionRequest.SerializeToString,
                response_deserializer=verification__pb2.RejectionTrace.FromString,
                _registered_method=True)
        self.StreamCausalLogs = channel.unary_stream(
                '/metacore.verification.v1.VerificationService/StreamCausalLogs',
                request_serializer=verification__pb2.RejectionRequest.SerializeToString,
                response_deserializer=verification__pb2.CausalLog.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/metacore.verification.v1.VerificationService/Health',
                request_serializer=verification__pb2.HealthRequest.SerializeToString,
                response_deserializer=common__pb2.Health.FromString,
                _registered_method=True)


class VerificationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Verify(self, request, context):
        """Blocking. The orchestrator waits on this; the firewall is not bypassable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRejections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCausalLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=verification__pb2.VerificationRequest.FromString,
                    response_serializer=verification__pb2.VerificationVerdict.SerializeToString,
            ),
            'StreamRejections': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRejections,
                    request_deserializer=verification__pb2.RejectionRequest.FromString,
                    response_serializer=verification__pb2.RejectionTrace.SerializeToString,
            ),
            'StreamCausalLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCausalLogs,
                    request_deserializer=verification__pb2.RejectionRequest.FromString,
                    response_serializer=verification__pb2.CausalLog.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=verification__pb2.HealthRequest.FromString,
                    response_serializer=common__pb2.Health.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metacore.verification.v1.VerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metacore.verification.v1.VerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VerificationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metacore.verification.v1.VerificationService/Verify',
            verification__pb2.VerificationRequest.SerializeToString,
            verification__pb2.VerificationVerdict.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRejections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.verification.v1.VerificationService/StreamRejections',
            verification__pb2.RejectionRequest.SerializeToString,
            verification__pb2.RejectionTrace.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCausalLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metacore.verification.v1.VerificationService/StreamCausalLogs',
            verification__pb2.RejectionRequest.SerializeToString,
            verification__pb2.CausalLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metacore.verification.v1.VerificationService/Health',
            verification__pb2.HealthRequest.SerializeToString,
            common__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
