// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data-quality flags travel with the state, never stripped. Module 2's epistemic uncertainty
// depends on being able to see a gap; imputed data presented as observed would hide it.
type Quality int32

const (
	Quality_QUALITY_UNSPECIFIED  Quality = 0
	Quality_QUALITY_OBSERVED     Quality = 1 // measured
	Quality_QUALITY_INTERPOLATED Quality = 2 // filled, and explicitly marked as filled
	Quality_QUALITY_MISSING      Quality = 3 // absent — downstream must treat as unknown, not as zero
	Quality_QUALITY_STALE        Quality = 4 // last known value, past its freshness budget
)

// Enum value maps for Quality.
var (
	Quality_name = map[int32]string{
		0: "QUALITY_UNSPECIFIED",
		1: "QUALITY_OBSERVED",
		2: "QUALITY_INTERPOLATED",
		3: "QUALITY_MISSING",
		4: "QUALITY_STALE",
	}
	Quality_value = map[string]int32{
		"QUALITY_UNSPECIFIED":  0,
		"QUALITY_OBSERVED":     1,
		"QUALITY_INTERPOLATED": 2,
		"QUALITY_MISSING":      3,
		"QUALITY_STALE":        4,
	}
)

func (x Quality) Enum() *Quality {
	p := new(Quality)
	*p = x
	return p
}

func (x Quality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quality) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Quality) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Quality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quality.Descriptor instead.
func (Quality) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Every cross-module message carries this so a consumer can detect a schema it was not built for.
type SchemaVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaVersion) Reset() {
	*x = SchemaVersion{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaVersion) ProtoMessage() {}

func (x *SchemaVersion) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaVersion.ProtoReflect.Descriptor instead.
func (*SchemaVersion) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *SchemaVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// Per-feature missingness mask accompanying any fused observation vector.
type QualityMask struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PerFeature       []Quality              `protobuf:"varint,1,rep,packed,name=per_feature,json=perFeature,proto3,enum=metacore.common.v1.Quality" json:"per_feature,omitempty"`
	ObservedFraction float32                `protobuf:"fixed32,2,opt,name=observed_fraction,json=observedFraction,proto3" json:"observed_fraction,omitempty"` // convenience: share of features with QUALITY_OBSERVED
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QualityMask) Reset() {
	*x = QualityMask{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityMask) ProtoMessage() {}

func (x *QualityMask) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityMask.ProtoReflect.Descriptor instead.
func (*QualityMask) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *QualityMask) GetPerFeature() []Quality {
	if x != nil {
		return x.PerFeature
	}
	return nil
}

func (x *QualityMask) GetObservedFraction() float32 {
	if x != nil {
		return x.ObservedFraction
	}
	return 0
}

// Identifies a replayable episode from the shared ID/OOD scenario library (owner: M1).
type ScenarioRef struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId        string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"` // e.g. "ditwah-2025-delft"
	LibraryVersion    string                 `protobuf:"bytes,2,opt,name=library_version,json=libraryVersion,proto3" json:"library_version,omitempty"`
	OutOfDistribution bool                   `protobuf:"varint,3,opt,name=out_of_distribution,json=outOfDistribution,proto3" json:"out_of_distribution,omitempty"` // label used for M2's OOD evaluation
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScenarioRef) Reset() {
	*x = ScenarioRef{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioRef) ProtoMessage() {}

func (x *ScenarioRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioRef.ProtoReflect.Descriptor instead.
func (*ScenarioRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ScenarioRef) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ScenarioRef) GetLibraryVersion() string {
	if x != nil {
		return x.LibraryVersion
	}
	return ""
}

func (x *ScenarioRef) GetOutOfDistribution() bool {
	if x != nil {
		return x.OutOfDistribution
	}
	return false
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EmittedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	Producer      string                 `protobuf:"bytes,3,opt,name=producer,proto3" json:"producer,omitempty"`              // "module1", "module2", ...
	Scenario      *ScenarioRef           `protobuf:"bytes,4,opt,name=scenario,proto3" json:"scenario,omitempty"`              // set during replay; empty in live operation
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // correlates one step across all four modules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *Envelope) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *Envelope) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *Envelope) GetScenario() *ScenarioRef {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type Health struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ready             bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Detail            string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	LastStepLatencyMs float64                `protobuf:"fixed64,3,opt,name=last_step_latency_ms,json=lastStepLatencyMs,proto3" json:"last_step_latency_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Health) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Health) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Health) GetLastStepLatencyMs() float64 {
	if x != nil {
		return x.LastStepLatencyMs
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x12metacore.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\rSchemaVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"x\n" +
	"\vQualityMask\x12<\n" +
	"\vper_feature\x18\x01 \x03(\x0e2\x1b.metacore.common.v1.QualityR\n" +
	"perFeature\x12+\n" +
	"\x11observed_fraction\x18\x02 \x01(\x02R\x10observedFraction\"\x87\x01\n" +
	"\vScenarioRef\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12'\n" +
	"\x0flibrary_version\x18\x02 \x01(\tR\x0elibraryVersion\x12.\n" +
	"\x13out_of_distribution\x18\x03 \x01(\bR\x11outOfDistribution\"\x83\x02\n" +
	"\bEnvelope\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.metacore.common.v1.SchemaVersionR\rschemaVersion\x129\n" +
	"\n" +
	"emitted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12\x1a\n" +
	"\bproducer\x18\x03 \x01(\tR\bproducer\x12;\n" +
	"\bscenario\x18\x04 \x01(\v2\x1f.metacore.common.v1.ScenarioRefR\bscenario\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"g\n" +
	"\x06Health\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12/\n" +
	"\x14last_step_latency_ms\x18\x03 \x01(\x01R\x11lastStepLatencyMs*z\n" +
	"\aQuality\x12\x17\n" +
	"\x13QUALITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10QUALITY_OBSERVED\x10\x01\x12\x18\n" +
	"\x14QUALITY_INTERPOLATED\x10\x02\x12\x13\n" +
	"\x0fQUALITY_MISSING\x10\x03\x12\x11\n" +
	"\rQUALITY_STALE\x10\x04B\xc4\x01\n" +
	"\x16com.metacore.common.v1B\vCommonProtoP\x01Z3github.com/metacore/contracts/go/common/v1;commonv1\xa2\x02\x03MCX\xaa\x02\x12Metacore.Common.V1\xca\x02\x12Metacore\\Common\\V1\xe2\x02\x1eMetacore\\Common\\V1\\GPBMetadata\xea\x02\x14Metacore::Common::V1b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_goTypes = []any{
	(Quality)(0),                  // 0: metacore.common.v1.Quality
	(*SchemaVersion)(nil),         // 1: metacore.common.v1.SchemaVersion
	(*QualityMask)(nil),           // 2: metacore.common.v1.QualityMask
	(*ScenarioRef)(nil),           // 3: metacore.common.v1.ScenarioRef
	(*Envelope)(nil),              // 4: metacore.common.v1.Envelope
	(*Health)(nil),                // 5: metacore.common.v1.Health
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	0, // 0: metacore.common.v1.QualityMask.per_feature:type_name -> metacore.common.v1.Quality
	1, // 1: metacore.common.v1.Envelope.schema_version:type_name -> metacore.common.v1.SchemaVersion
	6, // 2: metacore.common.v1.Envelope.emitted_at:type_name -> google.protobuf.Timestamp
	3, // 3: metacore.common.v1.Envelope.scenario:type_name -> metacore.common.v1.ScenarioRef
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
