// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: module2.proto

// Module 2 — Agentic Epistemic Uncertainty Quantification.
// Owner: Duwaragie K. (IT23270442). Consumer: M3.

package module2v1

import (
	v1 "github.com/metacore/contracts/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Dirichlet evidence over K grid-safety state classes, with the epistemic/aleatoric split.
type UncertaintyEstimate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Envelope         *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	KClasses         uint32                 `protobuf:"varint,2,opt,name=k_classes,json=kClasses,proto3" json:"k_classes,omitempty"`
	Evidence         []float32              `protobuf:"fixed32,3,rep,packed,name=evidence,proto3" json:"evidence,omitempty"`                         // per-class Dirichlet evidence
	TotalEvidence    float32                `protobuf:"fixed32,4,opt,name=total_evidence,json=totalEvidence,proto3" json:"total_evidence,omitempty"` // S
	Epistemic        float32                `protobuf:"fixed32,5,opt,name=epistemic,proto3" json:"epistemic,omitempty"`                              // u = K / S, in [0, 1]
	Aleatoric        float32                `protobuf:"fixed32,6,opt,name=aleatoric,proto3" json:"aleatoric,omitempty"`
	ClassProbability []float32              `protobuf:"fixed32,7,rep,packed,name=class_probability,json=classProbability,proto3" json:"class_probability,omitempty"`
	// Set when the input state carried missing modalities. Fail-safe: a malformed or absent input
	// must produce high epistemic uncertainty, never a confident signal.
	FailSafeTriggered bool `protobuf:"varint,8,opt,name=fail_safe_triggered,json=failSafeTriggered,proto3" json:"fail_safe_triggered,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UncertaintyEstimate) Reset() {
	*x = UncertaintyEstimate{}
	mi := &file_module2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncertaintyEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncertaintyEstimate) ProtoMessage() {}

func (x *UncertaintyEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_module2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncertaintyEstimate.ProtoReflect.Descriptor instead.
func (*UncertaintyEstimate) Descriptor() ([]byte, []int) {
	return file_module2_proto_rawDescGZIP(), []int{0}
}

func (x *UncertaintyEstimate) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *UncertaintyEstimate) GetKClasses() uint32 {
	if x != nil {
		return x.KClasses
	}
	return 0
}

func (x *UncertaintyEstimate) GetEvidence() []float32 {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *UncertaintyEstimate) GetTotalEvidence() float32 {
	if x != nil {
		return x.TotalEvidence
	}
	return 0
}

func (x *UncertaintyEstimate) GetEpistemic() float32 {
	if x != nil {
		return x.Epistemic
	}
	return 0
}

func (x *UncertaintyEstimate) GetAleatoric() float32 {
	if x != nil {
		return x.Aleatoric
	}
	return 0
}

func (x *UncertaintyEstimate) GetClassProbability() []float32 {
	if x != nil {
		return x.ClassProbability
	}
	return nil
}

func (x *UncertaintyEstimate) GetFailSafeTriggered() bool {
	if x != nil {
		return x.FailSafeTriggered
	}
	return false
}

// Discrete trigger with hysteresis so the gate does not chatter around the threshold.
type CompetenceDropTrigger struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Envelope         *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Active           bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Epistemic        float32                `protobuf:"fixed32,3,opt,name=epistemic,proto3" json:"epistemic,omitempty"`
	Threshold        float32                `protobuf:"fixed32,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	HysteresisBand   float32                `protobuf:"fixed32,5,opt,name=hysteresis_band,json=hysteresisBand,proto3" json:"hysteresis_band,omitempty"`
	ConsecutiveSteps uint64                 `protobuf:"varint,6,opt,name=consecutive_steps,json=consecutiveSteps,proto3" json:"consecutive_steps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompetenceDropTrigger) Reset() {
	*x = CompetenceDropTrigger{}
	mi := &file_module2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetenceDropTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetenceDropTrigger) ProtoMessage() {}

func (x *CompetenceDropTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_module2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetenceDropTrigger.ProtoReflect.Descriptor instead.
func (*CompetenceDropTrigger) Descriptor() ([]byte, []int) {
	return file_module2_proto_rawDescGZIP(), []int{1}
}

func (x *CompetenceDropTrigger) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *CompetenceDropTrigger) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CompetenceDropTrigger) GetEpistemic() float32 {
	if x != nil {
		return x.Epistemic
	}
	return 0
}

func (x *CompetenceDropTrigger) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CompetenceDropTrigger) GetHysteresisBand() float32 {
	if x != nil {
		return x.HysteresisBand
	}
	return 0
}

func (x *CompetenceDropTrigger) GetConsecutiveSteps() uint64 {
	if x != nil {
		return x.ConsecutiveSteps
	}
	return 0
}

type UncertaintyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *v1.ScenarioRef        `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncertaintyRequest) Reset() {
	*x = UncertaintyRequest{}
	mi := &file_module2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncertaintyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncertaintyRequest) ProtoMessage() {}

func (x *UncertaintyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncertaintyRequest.ProtoReflect.Descriptor instead.
func (*UncertaintyRequest) Descriptor() ([]byte, []int) {
	return file_module2_proto_rawDescGZIP(), []int{2}
}

func (x *UncertaintyRequest) GetScenario() *v1.ScenarioRef {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_module2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_module2_proto_rawDescGZIP(), []int{3}
}

var File_module2_proto protoreflect.FileDescriptor

const file_module2_proto_rawDesc = "" +
	"\n" +
	"\rmodule2.proto\x12\x13metacore.module2.v1\x1a\fcommon.proto\"\xc8\x02\n" +
	"\x13UncertaintyEstimate\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\tk_classes\x18\x02 \x01(\rR\bkClasses\x12\x1a\n" +
	"\bevidence\x18\x03 \x03(\x02R\bevidence\x12%\n" +
	"\x0etotal_evidence\x18\x04 \x01(\x02R\rtotalEvidence\x12\x1c\n" +
	"\tepistemic\x18\x05 \x01(\x02R\tepistemic\x12\x1c\n" +
	"\taleatoric\x18\x06 \x01(\x02R\taleatoric\x12+\n" +
	"\x11class_probability\x18\a \x03(\x02R\x10classProbability\x12.\n" +
	"\x13fail_safe_triggered\x18\b \x01(\bR\x11failSafeTriggered\"\xfb\x01\n" +
	"\x15CompetenceDropTrigger\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1c\n" +
	"\tepistemic\x18\x03 \x01(\x02R\tepistemic\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x02R\tthreshold\x12'\n" +
	"\x0fhysteresis_band\x18\x05 \x01(\x02R\x0ehysteresisBand\x12+\n" +
	"\x11consecutive_steps\x18\x06 \x01(\x04R\x10consecutiveSteps\"Q\n" +
	"\x12UncertaintyRequest\x12;\n" +
	"\bscenario\x18\x01 \x01(\v2\x1f.metacore.common.v1.ScenarioRefR\bscenario\"\x0f\n" +
	"\rHealthRequest2\xb0\x02\n" +
	"\x12UncertaintyService\x12h\n" +
	"\x11StreamUncertainty\x12'.metacore.module2.v1.UncertaintyRequest\x1a(.metacore.module2.v1.UncertaintyEstimate0\x01\x12f\n" +
	"\rStreamTrigger\x12'.metacore.module2.v1.UncertaintyRequest\x1a*.metacore.module2.v1.CompetenceDropTrigger0\x01\x12H\n" +
	"\x06Health\x12\".metacore.module2.v1.HealthRequest\x1a\x1a.metacore.common.v1.HealthB\xcc\x01\n" +
	"\x17com.metacore.module2.v1B\fModule2ProtoP\x01Z5github.com/metacore/contracts/go/module2/v1;module2v1\xa2\x02\x03MMX\xaa\x02\x13Metacore.Module2.V1\xca\x02\x13Metacore\\Module2\\V1\xe2\x02\x1fMetacore\\Module2\\V1\\GPBMetadata\xea\x02\x15Metacore::Module2::V1b\x06proto3"

var (
	file_module2_proto_rawDescOnce sync.Once
	file_module2_proto_rawDescData []byte
)

func file_module2_proto_rawDescGZIP() []byte {
	file_module2_proto_rawDescOnce.Do(func() {
		file_module2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module2_proto_rawDesc), len(file_module2_proto_rawDesc)))
	})
	return file_module2_proto_rawDescData
}

var file_module2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_module2_proto_goTypes = []any{
	(*UncertaintyEstimate)(nil),   // 0: metacore.module2.v1.UncertaintyEstimate
	(*CompetenceDropTrigger)(nil), // 1: metacore.module2.v1.CompetenceDropTrigger
	(*UncertaintyRequest)(nil),    // 2: metacore.module2.v1.UncertaintyRequest
	(*HealthRequest)(nil),         // 3: metacore.module2.v1.HealthRequest
	(*v1.Envelope)(nil),           // 4: metacore.common.v1.Envelope
	(*v1.ScenarioRef)(nil),        // 5: metacore.common.v1.ScenarioRef
	(*v1.Health)(nil),             // 6: metacore.common.v1.Health
}
var file_module2_proto_depIdxs = []int32{
	4, // 0: metacore.module2.v1.UncertaintyEstimate.envelope:type_name -> metacore.common.v1.Envelope
	4, // 1: metacore.module2.v1.CompetenceDropTrigger.envelope:type_name -> metacore.common.v1.Envelope
	5, // 2: metacore.module2.v1.UncertaintyRequest.scenario:type_name -> metacore.common.v1.ScenarioRef
	2, // 3: metacore.module2.v1.UncertaintyService.StreamUncertainty:input_type -> metacore.module2.v1.UncertaintyRequest
	2, // 4: metacore.module2.v1.UncertaintyService.StreamTrigger:input_type -> metacore.module2.v1.UncertaintyRequest
	3, // 5: metacore.module2.v1.UncertaintyService.Health:input_type -> metacore.module2.v1.HealthRequest
	0, // 6: metacore.module2.v1.UncertaintyService.StreamUncertainty:output_type -> metacore.module2.v1.UncertaintyEstimate
	1, // 7: metacore.module2.v1.UncertaintyService.StreamTrigger:output_type -> metacore.module2.v1.CompetenceDropTrigger
	6, // 8: metacore.module2.v1.UncertaintyService.Health:output_type -> metacore.common.v1.Health
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_module2_proto_init() }
func file_module2_proto_init() {
	if File_module2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module2_proto_rawDesc), len(file_module2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module2_proto_goTypes,
		DependencyIndexes: file_module2_proto_depIdxs,
		MessageInfos:      file_module2_proto_msgTypes,
	}.Build()
	File_module2_proto = out.File
	file_module2_proto_goTypes = nil
	file_module2_proto_depIdxs = nil
}
