// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: module1.proto

// Module 1 — Multi-Modal Spatiotemporal State Representation.
// Owner: Zayan M.F.M (IT23248212). Consumers: M2 (state), M3 (system context), M4 (topology).

package module1v1

import (
	v1 "github.com/metacore/contracts/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED AssetType = 0
	AssetType_ASSET_TYPE_BUS         AssetType = 1
	AssetType_ASSET_TYPE_PV          AssetType = 2
	AssetType_ASSET_TYPE_WIND        AssetType = 3
	AssetType_ASSET_TYPE_BESS        AssetType = 4
	AssetType_ASSET_TYPE_DIESEL      AssetType = 5
	AssetType_ASSET_TYPE_LOAD        AssetType = 6
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_BUS",
		2: "ASSET_TYPE_PV",
		3: "ASSET_TYPE_WIND",
		4: "ASSET_TYPE_BESS",
		5: "ASSET_TYPE_DIESEL",
		6: "ASSET_TYPE_LOAD",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED": 0,
		"ASSET_TYPE_BUS":         1,
		"ASSET_TYPE_PV":          2,
		"ASSET_TYPE_WIND":        3,
		"ASSET_TYPE_BESS":        4,
		"ASSET_TYPE_DIESEL":      5,
		"ASSET_TYPE_LOAD":        6,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_module1_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_module1_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{0}
}

type HazardSeverity int32

const (
	HazardSeverity_HAZARD_SEVERITY_UNSPECIFIED HazardSeverity = 0
	HazardSeverity_HAZARD_SEVERITY_NORMAL      HazardSeverity = 1
	HazardSeverity_HAZARD_SEVERITY_ELEVATED    HazardSeverity = 2
	HazardSeverity_HAZARD_SEVERITY_SEVERE      HazardSeverity = 3
	HazardSeverity_HAZARD_SEVERITY_EXTREME     HazardSeverity = 4
)

// Enum value maps for HazardSeverity.
var (
	HazardSeverity_name = map[int32]string{
		0: "HAZARD_SEVERITY_UNSPECIFIED",
		1: "HAZARD_SEVERITY_NORMAL",
		2: "HAZARD_SEVERITY_ELEVATED",
		3: "HAZARD_SEVERITY_SEVERE",
		4: "HAZARD_SEVERITY_EXTREME",
	}
	HazardSeverity_value = map[string]int32{
		"HAZARD_SEVERITY_UNSPECIFIED": 0,
		"HAZARD_SEVERITY_NORMAL":      1,
		"HAZARD_SEVERITY_ELEVATED":    2,
		"HAZARD_SEVERITY_SEVERE":      3,
		"HAZARD_SEVERITY_EXTREME":     4,
	}
)

func (x HazardSeverity) Enum() *HazardSeverity {
	p := new(HazardSeverity)
	*p = x
	return p
}

func (x HazardSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HazardSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_module1_proto_enumTypes[1].Descriptor()
}

func (HazardSeverity) Type() protoreflect.EnumType {
	return &file_module1_proto_enumTypes[1]
}

func (x HazardSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HazardSeverity.Descriptor instead.
func (HazardSeverity) EnumDescriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{1}
}

// ---------------------------------------------------------------- M1 -> M2
// The state representation. Frozen before the live stream exists so M2's evidential head can be
// sized against a real schema rather than a guess.
type StateRepresentation struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Envelope     *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	NodeCount    uint32                 `protobuf:"varint,2,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EmbeddingDim uint32                 `protobuf:"varint,3,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`
	// Flattened row-major [node_count x embedding_dim] learned node embedding.
	NodeEmbedding []float32 `protobuf:"fixed32,4,rep,packed,name=node_embedding,json=nodeEmbedding,proto3" json:"node_embedding,omitempty"`
	// Optional pooled graph-level embedding.
	GraphEmbedding []float32 `protobuf:"fixed32,5,rep,packed,name=graph_embedding,json=graphEmbedding,proto3" json:"graph_embedding,omitempty"`
	// Engineered features kept alongside the embedding so downstream ablations can use either.
	FeatureNames []string        `protobuf:"bytes,6,rep,name=feature_names,json=featureNames,proto3" json:"feature_names,omitempty"`
	NodeFeatures []float32       `protobuf:"fixed32,7,rep,packed,name=node_features,json=nodeFeatures,proto3" json:"node_features,omitempty"` // [node_count x len(feature_names)]
	Quality      *v1.QualityMask `protobuf:"bytes,8,opt,name=quality,proto3" json:"quality,omitempty"`
	// True when one or more modalities are absent (e.g. comms blackout). Never silently imputed.
	Degraded      bool `protobuf:"varint,9,opt,name=degraded,proto3" json:"degraded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRepresentation) Reset() {
	*x = StateRepresentation{}
	mi := &file_module1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRepresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRepresentation) ProtoMessage() {}

func (x *StateRepresentation) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRepresentation.ProtoReflect.Descriptor instead.
func (*StateRepresentation) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{0}
}

func (x *StateRepresentation) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *StateRepresentation) GetNodeCount() uint32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *StateRepresentation) GetEmbeddingDim() uint32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

func (x *StateRepresentation) GetNodeEmbedding() []float32 {
	if x != nil {
		return x.NodeEmbedding
	}
	return nil
}

func (x *StateRepresentation) GetGraphEmbedding() []float32 {
	if x != nil {
		return x.GraphEmbedding
	}
	return nil
}

func (x *StateRepresentation) GetFeatureNames() []string {
	if x != nil {
		return x.FeatureNames
	}
	return nil
}

func (x *StateRepresentation) GetNodeFeatures() []float32 {
	if x != nil {
		return x.NodeFeatures
	}
	return nil
}

func (x *StateRepresentation) GetQuality() *v1.QualityMask {
	if x != nil {
		return x.Quality
	}
	return nil
}

func (x *StateRepresentation) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

// ---------------------------------------------------------------- M1 -> M4
// The canonical network model. M1 and M4 must instantiate an identical physical state, so the
// topology is owned in one place and versioned.
type GridTopology struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Envelope          *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	TopologyId        string                 `protobuf:"bytes,2,opt,name=topology_id,json=topologyId,proto3" json:"topology_id,omitempty"` // e.g. "delft-3island-v1"
	OpendssMasterFile string                 `protobuf:"bytes,3,opt,name=opendss_master_file,json=opendssMasterFile,proto3" json:"opendss_master_file,omitempty"`
	Nodes             []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges             []*Edge                `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GridTopology) Reset() {
	*x = GridTopology{}
	mi := &file_module1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridTopology) ProtoMessage() {}

func (x *GridTopology) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridTopology.ProtoReflect.Descriptor instead.
func (*GridTopology) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{1}
}

func (x *GridTopology) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GridTopology) GetTopologyId() string {
	if x != nil {
		return x.TopologyId
	}
	return ""
}

func (x *GridTopology) GetOpendssMasterFile() string {
	if x != nil {
		return x.OpendssMasterFile
	}
	return ""
}

func (x *GridTopology) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GridTopology) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Node struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	NodeId       string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AssetType    AssetType              `protobuf:"varint,2,opt,name=asset_type,json=assetType,proto3,enum=metacore.module1.v1.AssetType" json:"asset_type,omitempty"`
	NominalKv    float64                `protobuf:"fixed64,3,opt,name=nominal_kv,json=nominalKv,proto3" json:"nominal_kv,omitempty"`
	CriticalLoad bool                   `protobuf:"varint,4,opt,name=critical_load,json=criticalLoad,proto3" json:"critical_load,omitempty"`
	// Published as arbitrary spatial offsets, never true coordinates (data governance).
	XOffset       float64 `protobuf:"fixed64,5,opt,name=x_offset,json=xOffset,proto3" json:"x_offset,omitempty"`
	YOffset       float64 `protobuf:"fixed64,6,opt,name=y_offset,json=yOffset,proto3" json:"y_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_module1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Node) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *Node) GetNominalKv() float64 {
	if x != nil {
		return x.NominalKv
	}
	return 0
}

func (x *Node) GetCriticalLoad() bool {
	if x != nil {
		return x.CriticalLoad
	}
	return false
}

func (x *Node) GetXOffset() float64 {
	if x != nil {
		return x.XOffset
	}
	return 0
}

func (x *Node) GetYOffset() float64 {
	if x != nil {
		return x.YOffset
	}
	return 0
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	FromNode      string                 `protobuf:"bytes,2,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,3,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	LengthKm      float64                `protobuf:"fixed64,4,opt,name=length_km,json=lengthKm,proto3" json:"length_km,omitempty"`
	AmpacityA     float64                `protobuf:"fixed64,5,opt,name=ampacity_a,json=ampacityA,proto3" json:"ampacity_a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_module1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{3}
}

func (x *Edge) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *Edge) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *Edge) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *Edge) GetLengthKm() float64 {
	if x != nil {
		return x.LengthKm
	}
	return 0
}

func (x *Edge) GetAmpacityA() float64 {
	if x != nil {
		return x.AmpacityA
	}
	return 0
}

// The electrical snapshot M4 loads into its digital twin.
type GridStateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	TopologyId    string                 `protobuf:"bytes,2,opt,name=topology_id,json=topologyId,proto3" json:"topology_id,omitempty"`
	NodeStates    []*NodeState           `protobuf:"bytes,3,rep,name=node_states,json=nodeStates,proto3" json:"node_states,omitempty"`
	UpdatePeriodS float64                `protobuf:"fixed64,4,opt,name=update_period_s,json=updatePeriodS,proto3" json:"update_period_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridStateSnapshot) Reset() {
	*x = GridStateSnapshot{}
	mi := &file_module1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridStateSnapshot) ProtoMessage() {}

func (x *GridStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridStateSnapshot.ProtoReflect.Descriptor instead.
func (*GridStateSnapshot) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{4}
}

func (x *GridStateSnapshot) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GridStateSnapshot) GetTopologyId() string {
	if x != nil {
		return x.TopologyId
	}
	return ""
}

func (x *GridStateSnapshot) GetNodeStates() []*NodeState {
	if x != nil {
		return x.NodeStates
	}
	return nil
}

func (x *GridStateSnapshot) GetUpdatePeriodS() float64 {
	if x != nil {
		return x.UpdatePeriodS
	}
	return 0
}

type NodeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VoltagePu     float64                `protobuf:"fixed64,2,opt,name=voltage_pu,json=voltagePu,proto3" json:"voltage_pu,omitempty"`
	PKw           float64                `protobuf:"fixed64,3,opt,name=p_kw,json=pKw,proto3" json:"p_kw,omitempty"`
	QKvar         float64                `protobuf:"fixed64,4,opt,name=q_kvar,json=qKvar,proto3" json:"q_kvar,omitempty"`
	SocFraction   float64                `protobuf:"fixed64,5,opt,name=soc_fraction,json=socFraction,proto3" json:"soc_fraction,omitempty"` // storage only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_module1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{5}
}

func (x *NodeState) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeState) GetVoltagePu() float64 {
	if x != nil {
		return x.VoltagePu
	}
	return 0
}

func (x *NodeState) GetPKw() float64 {
	if x != nil {
		return x.PKw
	}
	return 0
}

func (x *NodeState) GetQKvar() float64 {
	if x != nil {
		return x.QKvar
	}
	return 0
}

func (x *NodeState) GetSocFraction() float64 {
	if x != nil {
		return x.SocFraction
	}
	return 0
}

// ---------------------------------------------------------------- M1 -> M3
// Secondary input to the Meta-RL gate state, alongside M2's uncertainty scalar.
type SystemContext struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Envelope              *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	MaxNodeVulnerability  float32                `protobuf:"fixed32,2,opt,name=max_node_vulnerability,json=maxNodeVulnerability,proto3" json:"max_node_vulnerability,omitempty"` // 0..1
	MeanNodeVulnerability float32                `protobuf:"fixed32,3,opt,name=mean_node_vulnerability,json=meanNodeVulnerability,proto3" json:"mean_node_vulnerability,omitempty"`
	TopAtRiskNodes        []string               `protobuf:"bytes,4,rep,name=top_at_risk_nodes,json=topAtRiskNodes,proto3" json:"top_at_risk_nodes,omitempty"`
	TimeToHazardOnsetMin  float32                `protobuf:"fixed32,5,opt,name=time_to_hazard_onset_min,json=timeToHazardOnsetMin,proto3" json:"time_to_hazard_onset_min,omitempty"` // negative once the hazard has arrived
	Severity              HazardSeverity         `protobuf:"varint,6,opt,name=severity,proto3,enum=metacore.module1.v1.HazardSeverity" json:"severity,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SystemContext) Reset() {
	*x = SystemContext{}
	mi := &file_module1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemContext) ProtoMessage() {}

func (x *SystemContext) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemContext.ProtoReflect.Descriptor instead.
func (*SystemContext) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{6}
}

func (x *SystemContext) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SystemContext) GetMaxNodeVulnerability() float32 {
	if x != nil {
		return x.MaxNodeVulnerability
	}
	return 0
}

func (x *SystemContext) GetMeanNodeVulnerability() float32 {
	if x != nil {
		return x.MeanNodeVulnerability
	}
	return 0
}

func (x *SystemContext) GetTopAtRiskNodes() []string {
	if x != nil {
		return x.TopAtRiskNodes
	}
	return nil
}

func (x *SystemContext) GetTimeToHazardOnsetMin() float32 {
	if x != nil {
		return x.TimeToHazardOnsetMin
	}
	return 0
}

func (x *SystemContext) GetSeverity() HazardSeverity {
	if x != nil {
		return x.Severity
	}
	return HazardSeverity_HAZARD_SEVERITY_UNSPECIFIED
}

// Per-node forecast for the dashboard map view.
type VulnerabilityForecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	HorizonSteps  uint32                 `protobuf:"varint,2,opt,name=horizon_steps,json=horizonSteps,proto3" json:"horizon_steps,omitempty"`
	Nodes         []*NodeVulnerability   `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VulnerabilityForecast) Reset() {
	*x = VulnerabilityForecast{}
	mi := &file_module1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VulnerabilityForecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnerabilityForecast) ProtoMessage() {}

func (x *VulnerabilityForecast) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnerabilityForecast.ProtoReflect.Descriptor instead.
func (*VulnerabilityForecast) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{7}
}

func (x *VulnerabilityForecast) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *VulnerabilityForecast) GetHorizonSteps() uint32 {
	if x != nil {
		return x.HorizonSteps
	}
	return 0
}

func (x *VulnerabilityForecast) GetNodes() []*NodeVulnerability {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeVulnerability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ScorePerHorizon []float32              `protobuf:"fixed32,2,rep,packed,name=score_per_horizon,json=scorePerHorizon,proto3" json:"score_per_horizon,omitempty"` // 0..1, t+1 .. t+horizon_steps
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeVulnerability) Reset() {
	*x = NodeVulnerability{}
	mi := &file_module1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeVulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeVulnerability) ProtoMessage() {}

func (x *NodeVulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeVulnerability.ProtoReflect.Descriptor instead.
func (*NodeVulnerability) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{8}
}

func (x *NodeVulnerability) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeVulnerability) GetScorePerHorizon() []float32 {
	if x != nil {
		return x.ScorePerHorizon
	}
	return nil
}

type TopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopologyId    string                 `protobuf:"bytes,1,opt,name=topology_id,json=topologyId,proto3" json:"topology_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRequest) Reset() {
	*x = TopologyRequest{}
	mi := &file_module1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequest) ProtoMessage() {}

func (x *TopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequest.ProtoReflect.Descriptor instead.
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{9}
}

func (x *TopologyRequest) GetTopologyId() string {
	if x != nil {
		return x.TopologyId
	}
	return ""
}

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *v1.ScenarioRef        `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_module1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{10}
}

func (x *StateRequest) GetScenario() *v1.ScenarioRef {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_module1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_module1_proto_rawDescGZIP(), []int{11}
}

var File_module1_proto protoreflect.FileDescriptor

const file_module1_proto_rawDesc = "" +
	"\n" +
	"\rmodule1.proto\x12\x13metacore.module1.v1\x1a\fcommon.proto\"\x84\x03\n" +
	"\x13StateRepresentation\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1d\n" +
	"\n" +
	"node_count\x18\x02 \x01(\rR\tnodeCount\x12#\n" +
	"\rembedding_dim\x18\x03 \x01(\rR\fembeddingDim\x12%\n" +
	"\x0enode_embedding\x18\x04 \x03(\x02R\rnodeEmbedding\x12'\n" +
	"\x0fgraph_embedding\x18\x05 \x03(\x02R\x0egraphEmbedding\x12#\n" +
	"\rfeature_names\x18\x06 \x03(\tR\ffeatureNames\x12#\n" +
	"\rnode_features\x18\a \x03(\x02R\fnodeFeatures\x129\n" +
	"\aquality\x18\b \x01(\v2\x1f.metacore.common.v1.QualityMaskR\aquality\x12\x1a\n" +
	"\bdegraded\x18\t \x01(\bR\bdegraded\"\xfb\x01\n" +
	"\fGridTopology\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1f\n" +
	"\vtopology_id\x18\x02 \x01(\tR\n" +
	"topologyId\x12.\n" +
	"\x13opendss_master_file\x18\x03 \x01(\tR\x11opendssMasterFile\x12/\n" +
	"\x05nodes\x18\x04 \x03(\v2\x19.metacore.module1.v1.NodeR\x05nodes\x12/\n" +
	"\x05edges\x18\x05 \x03(\v2\x19.metacore.module1.v1.EdgeR\x05edges\"\xd8\x01\n" +
	"\x04Node\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12=\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\x0e2\x1e.metacore.module1.v1.AssetTypeR\tassetType\x12\x1d\n" +
	"\n" +
	"nominal_kv\x18\x03 \x01(\x01R\tnominalKv\x12#\n" +
	"\rcritical_load\x18\x04 \x01(\bR\fcriticalLoad\x12\x19\n" +
	"\bx_offset\x18\x05 \x01(\x01R\axOffset\x12\x19\n" +
	"\by_offset\x18\x06 \x01(\x01R\ayOffset\"\x91\x01\n" +
	"\x04Edge\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x1b\n" +
	"\tfrom_node\x18\x02 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x03 \x01(\tR\x06toNode\x12\x1b\n" +
	"\tlength_km\x18\x04 \x01(\x01R\blengthKm\x12\x1d\n" +
	"\n" +
	"ampacity_a\x18\x05 \x01(\x01R\tampacityA\"\xd7\x01\n" +
	"\x11GridStateSnapshot\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1f\n" +
	"\vtopology_id\x18\x02 \x01(\tR\n" +
	"topologyId\x12?\n" +
	"\vnode_states\x18\x03 \x03(\v2\x1e.metacore.module1.v1.NodeStateR\n" +
	"nodeStates\x12&\n" +
	"\x0fupdate_period_s\x18\x04 \x01(\x01R\rupdatePeriodS\"\x90\x01\n" +
	"\tNodeState\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"voltage_pu\x18\x02 \x01(\x01R\tvoltagePu\x12\x11\n" +
	"\x04p_kw\x18\x03 \x01(\x01R\x03pKw\x12\x15\n" +
	"\x06q_kvar\x18\x04 \x01(\x01R\x05qKvar\x12!\n" +
	"\fsoc_fraction\x18\x05 \x01(\x01R\vsocFraction\"\xdb\x02\n" +
	"\rSystemContext\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x124\n" +
	"\x16max_node_vulnerability\x18\x02 \x01(\x02R\x14maxNodeVulnerability\x126\n" +
	"\x17mean_node_vulnerability\x18\x03 \x01(\x02R\x15meanNodeVulnerability\x12)\n" +
	"\x11top_at_risk_nodes\x18\x04 \x03(\tR\x0etopAtRiskNodes\x126\n" +
	"\x18time_to_hazard_onset_min\x18\x05 \x01(\x02R\x14timeToHazardOnsetMin\x12?\n" +
	"\bseverity\x18\x06 \x01(\x0e2#.metacore.module1.v1.HazardSeverityR\bseverity\"\xb4\x01\n" +
	"\x15VulnerabilityForecast\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12#\n" +
	"\rhorizon_steps\x18\x02 \x01(\rR\fhorizonSteps\x12<\n" +
	"\x05nodes\x18\x03 \x03(\v2&.metacore.module1.v1.NodeVulnerabilityR\x05nodes\"X\n" +
	"\x11NodeVulnerability\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12*\n" +
	"\x11score_per_horizon\x18\x02 \x03(\x02R\x0fscorePerHorizon\"2\n" +
	"\x0fTopologyRequest\x12\x1f\n" +
	"\vtopology_id\x18\x01 \x01(\tR\n" +
	"topologyId\"K\n" +
	"\fStateRequest\x12;\n" +
	"\bscenario\x18\x01 \x01(\v2\x1f.metacore.common.v1.ScenarioRefR\bscenario\"\x0f\n" +
	"\rHealthRequest*\xa4\x01\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eASSET_TYPE_BUS\x10\x01\x12\x11\n" +
	"\rASSET_TYPE_PV\x10\x02\x12\x13\n" +
	"\x0fASSET_TYPE_WIND\x10\x03\x12\x13\n" +
	"\x0fASSET_TYPE_BESS\x10\x04\x12\x15\n" +
	"\x11ASSET_TYPE_DIESEL\x10\x05\x12\x13\n" +
	"\x0fASSET_TYPE_LOAD\x10\x06*\xa4\x01\n" +
	"\x0eHazardSeverity\x12\x1f\n" +
	"\x1bHAZARD_SEVERITY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16HAZARD_SEVERITY_NORMAL\x10\x01\x12\x1c\n" +
	"\x18HAZARD_SEVERITY_ELEVATED\x10\x02\x12\x1a\n" +
	"\x16HAZARD_SEVERITY_SEVERE\x10\x03\x12\x1b\n" +
	"\x17HAZARD_SEVERITY_EXTREME\x10\x042\xd5\x03\n" +
	"\x1aStateRepresentationService\x12V\n" +
	"\vGetTopology\x12$.metacore.module1.v1.TopologyRequest\x1a!.metacore.module1.v1.GridTopology\x12\\\n" +
	"\vStreamState\x12!.metacore.module1.v1.StateRequest\x1a(.metacore.module1.v1.StateRepresentation0\x01\x12]\n" +
	"\x0eStreamSnapshot\x12!.metacore.module1.v1.StateRequest\x1a&.metacore.module1.v1.GridStateSnapshot0\x01\x12X\n" +
	"\rStreamContext\x12!.metacore.module1.v1.StateRequest\x1a\".metacore.module1.v1.SystemContext0\x01\x12H\n" +
	"\x06Health\x12\".metacore.module1.v1.HealthRequest\x1a\x1a.metacore.common.v1.HealthB\xcc\x01\n" +
	"\x17com.metacore.module1.v1B\fModule1ProtoP\x01Z5github.com/metacore/contracts/go/module1/v1;module1v1\xa2\x02\x03MMX\xaa\x02\x13Metacore.Module1.V1\xca\x02\x13Metacore\\Module1\\V1\xe2\x02\x1fMetacore\\Module1\\V1\\GPBMetadata\xea\x02\x15Metacore::Module1::V1b\x06proto3"

var (
	file_module1_proto_rawDescOnce sync.Once
	file_module1_proto_rawDescData []byte
)

func file_module1_proto_rawDescGZIP() []byte {
	file_module1_proto_rawDescOnce.Do(func() {
		file_module1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module1_proto_rawDesc), len(file_module1_proto_rawDesc)))
	})
	return file_module1_proto_rawDescData
}

var file_module1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_module1_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_module1_proto_goTypes = []any{
	(AssetType)(0),                // 0: metacore.module1.v1.AssetType
	(HazardSeverity)(0),           // 1: metacore.module1.v1.HazardSeverity
	(*StateRepresentation)(nil),   // 2: metacore.module1.v1.StateRepresentation
	(*GridTopology)(nil),          // 3: metacore.module1.v1.GridTopology
	(*Node)(nil),                  // 4: metacore.module1.v1.Node
	(*Edge)(nil),                  // 5: metacore.module1.v1.Edge
	(*GridStateSnapshot)(nil),     // 6: metacore.module1.v1.GridStateSnapshot
	(*NodeState)(nil),             // 7: metacore.module1.v1.NodeState
	(*SystemContext)(nil),         // 8: metacore.module1.v1.SystemContext
	(*VulnerabilityForecast)(nil), // 9: metacore.module1.v1.VulnerabilityForecast
	(*NodeVulnerability)(nil),     // 10: metacore.module1.v1.NodeVulnerability
	(*TopologyRequest)(nil),       // 11: metacore.module1.v1.TopologyRequest
	(*StateRequest)(nil),          // 12: metacore.module1.v1.StateRequest
	(*HealthRequest)(nil),         // 13: metacore.module1.v1.HealthRequest
	(*v1.Envelope)(nil),           // 14: metacore.common.v1.Envelope
	(*v1.QualityMask)(nil),        // 15: metacore.common.v1.QualityMask
	(*v1.ScenarioRef)(nil),        // 16: metacore.common.v1.ScenarioRef
	(*v1.Health)(nil),             // 17: metacore.common.v1.Health
}
var file_module1_proto_depIdxs = []int32{
	14, // 0: metacore.module1.v1.StateRepresentation.envelope:type_name -> metacore.common.v1.Envelope
	15, // 1: metacore.module1.v1.StateRepresentation.quality:type_name -> metacore.common.v1.QualityMask
	14, // 2: metacore.module1.v1.GridTopology.envelope:type_name -> metacore.common.v1.Envelope
	4,  // 3: metacore.module1.v1.GridTopology.nodes:type_name -> metacore.module1.v1.Node
	5,  // 4: metacore.module1.v1.GridTopology.edges:type_name -> metacore.module1.v1.Edge
	0,  // 5: metacore.module1.v1.Node.asset_type:type_name -> metacore.module1.v1.AssetType
	14, // 6: metacore.module1.v1.GridStateSnapshot.envelope:type_name -> metacore.common.v1.Envelope
	7,  // 7: metacore.module1.v1.GridStateSnapshot.node_states:type_name -> metacore.module1.v1.NodeState
	14, // 8: metacore.module1.v1.SystemContext.envelope:type_name -> metacore.common.v1.Envelope
	1,  // 9: metacore.module1.v1.SystemContext.severity:type_name -> metacore.module1.v1.HazardSeverity
	14, // 10: metacore.module1.v1.VulnerabilityForecast.envelope:type_name -> metacore.common.v1.Envelope
	10, // 11: metacore.module1.v1.VulnerabilityForecast.nodes:type_name -> metacore.module1.v1.NodeVulnerability
	16, // 12: metacore.module1.v1.StateRequest.scenario:type_name -> metacore.common.v1.ScenarioRef
	11, // 13: metacore.module1.v1.StateRepresentationService.GetTopology:input_type -> metacore.module1.v1.TopologyRequest
	12, // 14: metacore.module1.v1.StateRepresentationService.StreamState:input_type -> metacore.module1.v1.StateRequest
	12, // 15: metacore.module1.v1.StateRepresentationService.StreamSnapshot:input_type -> metacore.module1.v1.StateRequest
	12, // 16: metacore.module1.v1.StateRepresentationService.StreamContext:input_type -> metacore.module1.v1.StateRequest
	13, // 17: metacore.module1.v1.StateRepresentationService.Health:input_type -> metacore.module1.v1.HealthRequest
	3,  // 18: metacore.module1.v1.StateRepresentationService.GetTopology:output_type -> metacore.module1.v1.GridTopology
	2,  // 19: metacore.module1.v1.StateRepresentationService.StreamState:output_type -> metacore.module1.v1.StateRepresentation
	6,  // 20: metacore.module1.v1.StateRepresentationService.StreamSnapshot:output_type -> metacore.module1.v1.GridStateSnapshot
	8,  // 21: metacore.module1.v1.StateRepresentationService.StreamContext:output_type -> metacore.module1.v1.SystemContext
	17, // 22: metacore.module1.v1.StateRepresentationService.Health:output_type -> metacore.common.v1.Health
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_module1_proto_init() }
func file_module1_proto_init() {
	if File_module1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module1_proto_rawDesc), len(file_module1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module1_proto_goTypes,
		DependencyIndexes: file_module1_proto_depIdxs,
		EnumInfos:         file_module1_proto_enumTypes,
		MessageInfos:      file_module1_proto_msgTypes,
	}.Build()
	File_module1_proto = out.File
	file_module1_proto_goTypes = nil
	file_module1_proto_depIdxs = nil
}
