// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: module3.proto

// Module 3 — Cost-Aware Metacognitive Gating & Meta-Policy.
// Owner: Saabir S. (IT23432598). Consumer: M4.

package module3v1

import (
	v1 "github.com/metacore/contracts/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessPath int32

const (
	ProcessPath_PROCESS_PATH_UNSPECIFIED ProcessPath = 0
	ProcessPath_PROCESS_PATH_SYSTEM1     ProcessPath = 1 // fast rule-based reactive path
	ProcessPath_PROCESS_PATH_SYSTEM2     ProcessPath = 2 // deliberative survival optimisation
)

// Enum value maps for ProcessPath.
var (
	ProcessPath_name = map[int32]string{
		0: "PROCESS_PATH_UNSPECIFIED",
		1: "PROCESS_PATH_SYSTEM1",
		2: "PROCESS_PATH_SYSTEM2",
	}
	ProcessPath_value = map[string]int32{
		"PROCESS_PATH_UNSPECIFIED": 0,
		"PROCESS_PATH_SYSTEM1":     1,
		"PROCESS_PATH_SYSTEM2":     2,
	}
)

func (x ProcessPath) Enum() *ProcessPath {
	p := new(ProcessPath)
	*p = x
	return p
}

func (x ProcessPath) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessPath) Descriptor() protoreflect.EnumDescriptor {
	return file_module3_proto_enumTypes[0].Descriptor()
}

func (ProcessPath) Type() protoreflect.EnumType {
	return &file_module3_proto_enumTypes[0]
}

func (x ProcessPath) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessPath.Descriptor instead.
func (ProcessPath) EnumDescriptor() ([]byte, []int) {
	return file_module3_proto_rawDescGZIP(), []int{0}
}

// The single action emitted per step, from either System 1 or System 2. Every field is something
// M4 can apply to the digital twin — nothing here is advisory.
type ProposedControlAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ActionId      string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Origin        ProcessPath            `protobuf:"varint,3,opt,name=origin,proto3,enum=metacore.module3.v1.ProcessPath" json:"origin,omitempty"`
	Breakers      []*BreakerCommand      `protobuf:"bytes,4,rep,name=breakers,proto3" json:"breakers,omitempty"`
	LoadShed      []*LoadShedCommand     `protobuf:"bytes,5,rep,name=load_shed,json=loadShed,proto3" json:"load_shed,omitempty"`
	Dispatch      []*DispatchSetpoint    `protobuf:"bytes,6,rep,name=dispatch,proto3" json:"dispatch,omitempty"`
	Rationale     string                 `protobuf:"bytes,7,opt,name=rationale,proto3" json:"rationale,omitempty"` // short human-readable summary for the dashboard
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposedControlAction) Reset() {
	*x = ProposedControlAction{}
	mi := &file_module3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposedControlAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposedControlAction) ProtoMessage() {}

func (x *ProposedControlAction) ProtoReflect() protoreflect.Message {
	mi := &file_module3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposedControlAction.ProtoReflect.Descriptor instead.
func (*ProposedControlAction) Descriptor() ([]byte, []int) {
	return file_module3_proto_rawDescGZIP(), []int{0}
}

func (x *ProposedControlAction) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *ProposedControlAction) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ProposedControlAction) GetOrigin() ProcessPath {
	if x != nil {
		return x.Origin
	}
	return ProcessPath_PROCESS_PATH_UNSPECIFIED
}

func (x *ProposedControlAction) GetBreakers() []*BreakerCommand {
	if x != nil {
		return x.Breakers
	}
	return nil
}

func (x *ProposedControlAction) GetLoadShed() []*LoadShedCommand {
	if x != nil {
		return x.LoadShed
	}
	return nil
}

func (x *ProposedControlAction) GetDispatch() []*DispatchSetpoint {
	if x != nil {
		return x.Dispatch
	}
	return nil
}

func (x *ProposedControlAction) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type BreakerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Closed        bool                   `protobuf:"varint,2,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakerCommand) Reset() {
	*x = BreakerCommand{}
	mi := &file_module3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakerCommand) ProtoMessage() {}

func (x *BreakerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_module3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakerCommand.ProtoReflect.Descriptor instead.
func (*BreakerCommand) Descriptor() ([]byte, []int) {
	return file_module3_proto_rawDescGZIP(), []int{1}
}

func (x *BreakerCommand) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *BreakerCommand) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type LoadShedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ShedFraction  float32                `protobuf:"fixed32,2,opt,name=shed_fraction,json=shedFraction,proto3" json:"shed_fraction,omitempty"` // 0..1
	PriorityTier  uint32                 `protobuf:"varint,3,opt,name=priority_tier,json=priorityTier,proto3" json:"priority_tier,omitempty"`  // 1 = most critical, never shed before higher tiers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadShedCommand) Reset() {
	*x = LoadShedCommand{}
	mi := &file_module3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadShedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadShedCommand) ProtoMessage() {}

func (x *LoadShedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_module3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadShedCommand.ProtoReflect.Descriptor instead.
func (*LoadShedCommand) Descriptor() ([]byte, []int) {
	return file_module3_proto_rawDescGZIP(), []int{2}
}

func (x *LoadShedCommand) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LoadShedCommand) GetShedFraction() float32 {
	if x != nil {
		return x.ShedFraction
	}
	return 0
}

func (x *LoadShedCommand) GetPriorityTier() uint32 {
	if x != nil {
		return x.PriorityTier
	}
	return 0
}

type DispatchSetpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PKw           float64                `protobuf:"fixed64,2,opt,name=p_kw,json=pKw,proto3" json:"p_kw,omitempty"`
	QKvar         float64                `protobuf:"fixed64,3,opt,name=q_kvar,json=qKvar,proto3" json:"q_kvar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchSetpoint) Reset() {
	*x = DispatchSetpoint{}
	mi := &file_module3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchSetpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchSetpoint) ProtoMessage() {}

func (x *DispatchSetpoint) ProtoReflect() protoreflect.Message {
	mi := &file_module3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchSetpoint.ProtoReflect.Descriptor instead.
func (*DispatchSetpoint) Descriptor() ([]byte, []int) {
	return file_module3_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchSetpoint) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DispatchSetpoint) GetPKw() float64 {
	if x != nil {
		return x.PKw
	}
	return 0
}

func (x *DispatchSetpoint) GetQKvar() float64 {
	if x != nil {
		return x.QKvar
	}
	return 0
}

// Emitted alongside every action for audit, ablation and the dashboard gating timeline.
type GatingDecision struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Envelope                *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ActionId                string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Chosen                  ProcessPath            `protobuf:"varint,3,opt,name=chosen,proto3,enum=metacore.module3.v1.ProcessPath" json:"chosen,omitempty"`
	EpistemicAtDecision     float32                `protobuf:"fixed32,4,opt,name=epistemic_at_decision,json=epistemicAtDecision,proto3" json:"epistemic_at_decision,omitempty"`
	ExpectedSurvivalBenefit float32                `protobuf:"fixed32,5,opt,name=expected_survival_benefit,json=expectedSurvivalBenefit,proto3" json:"expected_survival_benefit,omitempty"`
	DeliberationCost        float32                `protobuf:"fixed32,6,opt,name=deliberation_cost,json=deliberationCost,proto3" json:"deliberation_cost,omitempty"`
	LatencyMs               float64                `protobuf:"fixed64,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	BudgetExhaustedFallback bool                   `protobuf:"varint,8,opt,name=budget_exhausted_fallback,json=budgetExhaustedFallback,proto3" json:"budget_exhausted_fallback,omitempty"` // true when System 1 was taken because the budget ran out
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GatingDecision) Reset() {
	*x = GatingDecision{}
	mi := &file_module3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatingDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatingDecision) ProtoMessage() {}

func (x *GatingDecision) ProtoReflect() protoreflect.Message {
	mi := &file_module3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatingDecision.ProtoReflect.Descriptor instead.
func (*GatingDecision) Descriptor() ([]byte, []int) {
	return file_module3_proto_rawDescGZIP(), []int{4}
}

func (x *GatingDecision) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GatingDecision) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *GatingDecision) GetChosen() ProcessPath {
	if x != nil {
		return x.Chosen
	}
	return ProcessPath_PROCESS_PATH_UNSPECIFIED
}

func (x *GatingDecision) GetEpistemicAtDecision() float32 {
	if x != nil {
		return x.EpistemicAtDecision
	}
	return 0
}

func (x *GatingDecision) GetExpectedSurvivalBenefit() float32 {
	if x != nil {
		return x.ExpectedSurvivalBenefit
	}
	return 0
}

func (x *GatingDecision) GetDeliberationCost() float32 {
	if x != nil {
		return x.DeliberationCost
	}
	return 0
}

func (x *GatingDecision) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *GatingDecision) GetBudgetExhaustedFallback() bool {
	if x != nil {
		return x.BudgetExhaustedFallback
	}
	return false
}

type GatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *v1.ScenarioRef        `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatingRequest) Reset() {
	*x = GatingRequest{}
	mi := &file_module3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatingRequest) ProtoMessage() {}

func (x *GatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatingRequest.ProtoReflect.Descriptor instead.
func (*GatingRequest) Descriptor() ([]byte, []int) {
	return file_module3_proto_rawDescGZIP(), []int{5}
}

func (x *GatingRequest) GetScenario() *v1.ScenarioRef {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_module3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_module3_proto_rawDescGZIP(), []int{6}
}

var File_module3_proto protoreflect.FileDescriptor

const file_module3_proto_rawDesc = "" +
	"\n" +
	"\rmodule3.proto\x12\x13metacore.module3.v1\x1a\fcommon.proto\"\x8d\x03\n" +
	"\x15ProposedControlAction\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x128\n" +
	"\x06origin\x18\x03 \x01(\x0e2 .metacore.module3.v1.ProcessPathR\x06origin\x12?\n" +
	"\bbreakers\x18\x04 \x03(\v2#.metacore.module3.v1.BreakerCommandR\bbreakers\x12A\n" +
	"\tload_shed\x18\x05 \x03(\v2$.metacore.module3.v1.LoadShedCommandR\bloadShed\x12A\n" +
	"\bdispatch\x18\x06 \x03(\v2%.metacore.module3.v1.DispatchSetpointR\bdispatch\x12\x1c\n" +
	"\trationale\x18\a \x01(\tR\trationale\"A\n" +
	"\x0eBreakerCommand\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x16\n" +
	"\x06closed\x18\x02 \x01(\bR\x06closed\"t\n" +
	"\x0fLoadShedCommand\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rshed_fraction\x18\x02 \x01(\x02R\fshedFraction\x12#\n" +
	"\rpriority_tier\x18\x03 \x01(\rR\fpriorityTier\"U\n" +
	"\x10DispatchSetpoint\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x11\n" +
	"\x04p_kw\x18\x02 \x01(\x01R\x03pKw\x12\x15\n" +
	"\x06q_kvar\x18\x03 \x01(\x01R\x05qKvar\"\x99\x03\n" +
	"\x0eGatingDecision\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x128\n" +
	"\x06chosen\x18\x03 \x01(\x0e2 .metacore.module3.v1.ProcessPathR\x06chosen\x122\n" +
	"\x15epistemic_at_decision\x18\x04 \x01(\x02R\x13epistemicAtDecision\x12:\n" +
	"\x19expected_survival_benefit\x18\x05 \x01(\x02R\x17expectedSurvivalBenefit\x12+\n" +
	"\x11deliberation_cost\x18\x06 \x01(\x02R\x10deliberationCost\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x01R\tlatencyMs\x12:\n" +
	"\x19budget_exhausted_fallback\x18\b \x01(\bR\x17budgetExhaustedFallback\"L\n" +
	"\rGatingRequest\x12;\n" +
	"\bscenario\x18\x01 \x01(\v2\x1f.metacore.common.v1.ScenarioRefR\bscenario\"\x0f\n" +
	"\rHealthRequest*_\n" +
	"\vProcessPath\x12\x1c\n" +
	"\x18PROCESS_PATH_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROCESS_PATH_SYSTEM1\x10\x01\x12\x18\n" +
	"\x14PROCESS_PATH_SYSTEM2\x10\x022\x98\x02\n" +
	"\rGatingService\x12`\n" +
	"\fStreamAction\x12\".metacore.module3.v1.GatingRequest\x1a*.metacore.module3.v1.ProposedControlAction0\x01\x12[\n" +
	"\x0eStreamDecision\x12\".metacore.module3.v1.GatingRequest\x1a#.metacore.module3.v1.GatingDecision0\x01\x12H\n" +
	"\x06Health\x12\".metacore.module3.v1.HealthRequest\x1a\x1a.metacore.common.v1.HealthB\xcc\x01\n" +
	"\x17com.metacore.module3.v1B\fModule3ProtoP\x01Z5github.com/metacore/contracts/go/module3/v1;module3v1\xa2\x02\x03MMX\xaa\x02\x13Metacore.Module3.V1\xca\x02\x13Metacore\\Module3\\V1\xe2\x02\x1fMetacore\\Module3\\V1\\GPBMetadata\xea\x02\x15Metacore::Module3::V1b\x06proto3"

var (
	file_module3_proto_rawDescOnce sync.Once
	file_module3_proto_rawDescData []byte
)

func file_module3_proto_rawDescGZIP() []byte {
	file_module3_proto_rawDescOnce.Do(func() {
		file_module3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module3_proto_rawDesc), len(file_module3_proto_rawDesc)))
	})
	return file_module3_proto_rawDescData
}

var file_module3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_module3_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_module3_proto_goTypes = []any{
	(ProcessPath)(0),              // 0: metacore.module3.v1.ProcessPath
	(*ProposedControlAction)(nil), // 1: metacore.module3.v1.ProposedControlAction
	(*BreakerCommand)(nil),        // 2: metacore.module3.v1.BreakerCommand
	(*LoadShedCommand)(nil),       // 3: metacore.module3.v1.LoadShedCommand
	(*DispatchSetpoint)(nil),      // 4: metacore.module3.v1.DispatchSetpoint
	(*GatingDecision)(nil),        // 5: metacore.module3.v1.GatingDecision
	(*GatingRequest)(nil),         // 6: metacore.module3.v1.GatingRequest
	(*HealthRequest)(nil),         // 7: metacore.module3.v1.HealthRequest
	(*v1.Envelope)(nil),           // 8: metacore.common.v1.Envelope
	(*v1.ScenarioRef)(nil),        // 9: metacore.common.v1.ScenarioRef
	(*v1.Health)(nil),             // 10: metacore.common.v1.Health
}
var file_module3_proto_depIdxs = []int32{
	8,  // 0: metacore.module3.v1.ProposedControlAction.envelope:type_name -> metacore.common.v1.Envelope
	0,  // 1: metacore.module3.v1.ProposedControlAction.origin:type_name -> metacore.module3.v1.ProcessPath
	2,  // 2: metacore.module3.v1.ProposedControlAction.breakers:type_name -> metacore.module3.v1.BreakerCommand
	3,  // 3: metacore.module3.v1.ProposedControlAction.load_shed:type_name -> metacore.module3.v1.LoadShedCommand
	4,  // 4: metacore.module3.v1.ProposedControlAction.dispatch:type_name -> metacore.module3.v1.DispatchSetpoint
	8,  // 5: metacore.module3.v1.GatingDecision.envelope:type_name -> metacore.common.v1.Envelope
	0,  // 6: metacore.module3.v1.GatingDecision.chosen:type_name -> metacore.module3.v1.ProcessPath
	9,  // 7: metacore.module3.v1.GatingRequest.scenario:type_name -> metacore.common.v1.ScenarioRef
	6,  // 8: metacore.module3.v1.GatingService.StreamAction:input_type -> metacore.module3.v1.GatingRequest
	6,  // 9: metacore.module3.v1.GatingService.StreamDecision:input_type -> metacore.module3.v1.GatingRequest
	7,  // 10: metacore.module3.v1.GatingService.Health:input_type -> metacore.module3.v1.HealthRequest
	1,  // 11: metacore.module3.v1.GatingService.StreamAction:output_type -> metacore.module3.v1.ProposedControlAction
	5,  // 12: metacore.module3.v1.GatingService.StreamDecision:output_type -> metacore.module3.v1.GatingDecision
	10, // 13: metacore.module3.v1.GatingService.Health:output_type -> metacore.common.v1.Health
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_module3_proto_init() }
func file_module3_proto_init() {
	if File_module3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module3_proto_rawDesc), len(file_module3_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module3_proto_goTypes,
		DependencyIndexes: file_module3_proto_depIdxs,
		EnumInfos:         file_module3_proto_enumTypes,
		MessageInfos:      file_module3_proto_msgTypes,
	}.Build()
	File_module3_proto = out.File
	file_module3_proto_goTypes = nil
	file_module3_proto_depIdxs = nil
}
