// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: module1.proto

// Module 1 — Multi-Modal Spatiotemporal State Representation.
// Owner: Zayan M.F.M (IT23248212). Consumers: M2 (state), M3 (system context), M4 (topology).

package module1v1

import (
	context "context"
	v1 "github.com/metacore/contracts/go/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StateRepresentationService_GetTopology_FullMethodName    = "/metacore.module1.v1.StateRepresentationService/GetTopology"
	StateRepresentationService_StreamState_FullMethodName    = "/metacore.module1.v1.StateRepresentationService/StreamState"
	StateRepresentationService_StreamSnapshot_FullMethodName = "/metacore.module1.v1.StateRepresentationService/StreamSnapshot"
	StateRepresentationService_StreamContext_FullMethodName  = "/metacore.module1.v1.StateRepresentationService/StreamContext"
	StateRepresentationService_Health_FullMethodName         = "/metacore.module1.v1.StateRepresentationService/Health"
)

// StateRepresentationServiceClient is the client API for StateRepresentationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateRepresentationServiceClient interface {
	GetTopology(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*GridTopology, error)
	StreamState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateRepresentation], error)
	StreamSnapshot(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GridStateSnapshot], error)
	StreamContext(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemContext], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*v1.Health, error)
}

type stateRepresentationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateRepresentationServiceClient(cc grpc.ClientConnInterface) StateRepresentationServiceClient {
	return &stateRepresentationServiceClient{cc}
}

func (c *stateRepresentationServiceClient) GetTopology(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*GridTopology, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GridTopology)
	err := c.cc.Invoke(ctx, StateRepresentationService_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateRepresentationServiceClient) StreamState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateRepresentation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateRepresentationService_ServiceDesc.Streams[0], StateRepresentationService_StreamState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateRequest, StateRepresentation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateRepresentationService_StreamStateClient = grpc.ServerStreamingClient[StateRepresentation]

func (c *stateRepresentationServiceClient) StreamSnapshot(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GridStateSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateRepresentationService_ServiceDesc.Streams[1], StateRepresentationService_StreamSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateRequest, GridStateSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateRepresentationService_StreamSnapshotClient = grpc.ServerStreamingClient[GridStateSnapshot]

func (c *stateRepresentationServiceClient) StreamContext(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemContext], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateRepresentationService_ServiceDesc.Streams[2], StateRepresentationService_StreamContext_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateRequest, SystemContext]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateRepresentationService_StreamContextClient = grpc.ServerStreamingClient[SystemContext]

func (c *stateRepresentationServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*v1.Health, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Health)
	err := c.cc.Invoke(ctx, StateRepresentationService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateRepresentationServiceServer is the server API for StateRepresentationService service.
// All implementations must embed UnimplementedStateRepresentationServiceServer
// for forward compatibility.
type StateRepresentationServiceServer interface {
	GetTopology(context.Context, *TopologyRequest) (*GridTopology, error)
	StreamState(*StateRequest, grpc.ServerStreamingServer[StateRepresentation]) error
	StreamSnapshot(*StateRequest, grpc.ServerStreamingServer[GridStateSnapshot]) error
	StreamContext(*StateRequest, grpc.ServerStreamingServer[SystemContext]) error
	Health(context.Context, *HealthRequest) (*v1.Health, error)
	mustEmbedUnimplementedStateRepresentationServiceServer()
}

// UnimplementedStateRepresentationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateRepresentationServiceServer struct{}

func (UnimplementedStateRepresentationServiceServer) GetTopology(context.Context, *TopologyRequest) (*GridTopology, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedStateRepresentationServiceServer) StreamState(*StateRequest, grpc.ServerStreamingServer[StateRepresentation]) error {
	return status.Error(codes.Unimplemented, "method StreamState not implemented")
}
func (UnimplementedStateRepresentationServiceServer) StreamSnapshot(*StateRequest, grpc.ServerStreamingServer[GridStateSnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamSnapshot not implemented")
}
func (UnimplementedStateRepresentationServiceServer) StreamContext(*StateRequest, grpc.ServerStreamingServer[SystemContext]) error {
	return status.Error(codes.Unimplemented, "method StreamContext not implemented")
}
func (UnimplementedStateRepresentationServiceServer) Health(context.Context, *HealthRequest) (*v1.Health, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedStateRepresentationServiceServer) mustEmbedUnimplementedStateRepresentationServiceServer() {
}
func (UnimplementedStateRepresentationServiceServer) testEmbeddedByValue() {}

// UnsafeStateRepresentationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateRepresentationServiceServer will
// result in compilation errors.
type UnsafeStateRepresentationServiceServer interface {
	mustEmbedUnimplementedStateRepresentationServiceServer()
}

func RegisterStateRepresentationServiceServer(s grpc.ServiceRegistrar, srv StateRepresentationServiceServer) {
	// If the following call panics, it indicates UnimplementedStateRepresentationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateRepresentationService_ServiceDesc, srv)
}

func _StateRepresentationService_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateRepresentationServiceServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateRepresentationService_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateRepresentationServiceServer).GetTopology(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateRepresentationService_StreamState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateRepresentationServiceServer).StreamState(m, &grpc.GenericServerStream[StateRequest, StateRepresentation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateRepresentationService_StreamStateServer = grpc.ServerStreamingServer[StateRepresentation]

func _StateRepresentationService_StreamSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateRepresentationServiceServer).StreamSnapshot(m, &grpc.GenericServerStream[StateRequest, GridStateSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateRepresentationService_StreamSnapshotServer = grpc.ServerStreamingServer[GridStateSnapshot]

func _StateRepresentationService_StreamContext_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateRepresentationServiceServer).StreamContext(m, &grpc.GenericServerStream[StateRequest, SystemContext]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateRepresentationService_StreamContextServer = grpc.ServerStreamingServer[SystemContext]

func _StateRepresentationService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateRepresentationServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateRepresentationService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateRepresentationServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateRepresentationService_ServiceDesc is the grpc.ServiceDesc for StateRepresentationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateRepresentationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metacore.module1.v1.StateRepresentationService",
	HandlerType: (*StateRepresentationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopology",
			Handler:    _StateRepresentationService_GetTopology_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _StateRepresentationService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamState",
			Handler:       _StateRepresentationService_StreamState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSnapshot",
			Handler:       _StateRepresentationService_StreamSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamContext",
			Handler:       _StateRepresentationService_StreamContext_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "module1.proto",
}
