// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: module3.proto

// Module 3 — Cost-Aware Metacognitive Gating & Meta-Policy.
// Owner: Saabir S. (IT23432598). Consumer: M4.

package module3v1

import (
	context "context"
	v1 "github.com/metacore/contracts/go/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatingService_StreamAction_FullMethodName   = "/metacore.module3.v1.GatingService/StreamAction"
	GatingService_StreamDecision_FullMethodName = "/metacore.module3.v1.GatingService/StreamDecision"
	GatingService_Health_FullMethodName         = "/metacore.module3.v1.GatingService/Health"
)

// GatingServiceClient is the client API for GatingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatingServiceClient interface {
	StreamAction(ctx context.Context, in *GatingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProposedControlAction], error)
	StreamDecision(ctx context.Context, in *GatingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GatingDecision], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*v1.Health, error)
}

type gatingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatingServiceClient(cc grpc.ClientConnInterface) GatingServiceClient {
	return &gatingServiceClient{cc}
}

func (c *gatingServiceClient) StreamAction(ctx context.Context, in *GatingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProposedControlAction], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatingService_ServiceDesc.Streams[0], GatingService_StreamAction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatingRequest, ProposedControlAction]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatingService_StreamActionClient = grpc.ServerStreamingClient[ProposedControlAction]

func (c *gatingServiceClient) StreamDecision(ctx context.Context, in *GatingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GatingDecision], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatingService_ServiceDesc.Streams[1], GatingService_StreamDecision_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatingRequest, GatingDecision]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatingService_StreamDecisionClient = grpc.ServerStreamingClient[GatingDecision]

func (c *gatingServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*v1.Health, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Health)
	err := c.cc.Invoke(ctx, GatingService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatingServiceServer is the server API for GatingService service.
// All implementations must embed UnimplementedGatingServiceServer
// for forward compatibility.
type GatingServiceServer interface {
	StreamAction(*GatingRequest, grpc.ServerStreamingServer[ProposedControlAction]) error
	StreamDecision(*GatingRequest, grpc.ServerStreamingServer[GatingDecision]) error
	Health(context.Context, *HealthRequest) (*v1.Health, error)
	mustEmbedUnimplementedGatingServiceServer()
}

// UnimplementedGatingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatingServiceServer struct{}

func (UnimplementedGatingServiceServer) StreamAction(*GatingRequest, grpc.ServerStreamingServer[ProposedControlAction]) error {
	return status.Error(codes.Unimplemented, "method StreamAction not implemented")
}
func (UnimplementedGatingServiceServer) StreamDecision(*GatingRequest, grpc.ServerStreamingServer[GatingDecision]) error {
	return status.Error(codes.Unimplemented, "method StreamDecision not implemented")
}
func (UnimplementedGatingServiceServer) Health(context.Context, *HealthRequest) (*v1.Health, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGatingServiceServer) mustEmbedUnimplementedGatingServiceServer() {}
func (UnimplementedGatingServiceServer) testEmbeddedByValue()                       {}

// UnsafeGatingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatingServiceServer will
// result in compilation errors.
type UnsafeGatingServiceServer interface {
	mustEmbedUnimplementedGatingServiceServer()
}

func RegisterGatingServiceServer(s grpc.ServiceRegistrar, srv GatingServiceServer) {
	// If the following call panics, it indicates UnimplementedGatingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatingService_ServiceDesc, srv)
}

func _GatingService_StreamAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GatingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatingServiceServer).StreamAction(m, &grpc.GenericServerStream[GatingRequest, ProposedControlAction]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatingService_StreamActionServer = grpc.ServerStreamingServer[ProposedControlAction]

func _GatingService_StreamDecision_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GatingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatingServiceServer).StreamDecision(m, &grpc.GenericServerStream[GatingRequest, GatingDecision]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatingService_StreamDecisionServer = grpc.ServerStreamingServer[GatingDecision]

func _GatingService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatingServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatingService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatingServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatingService_ServiceDesc is the grpc.ServiceDesc for GatingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metacore.module3.v1.GatingService",
	HandlerType: (*GatingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _GatingService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAction",
			Handler:       _GatingService_StreamAction_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamDecision",
			Handler:       _GatingService_StreamDecision_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "module3.proto",
}
