// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: module2.proto

// Module 2 — Agentic Epistemic Uncertainty Quantification.
// Owner: Duwaragie K. (IT23270442). Consumer: M3.

package module2v1

import (
	context "context"
	v1 "github.com/metacore/contracts/go/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UncertaintyService_StreamUncertainty_FullMethodName = "/metacore.module2.v1.UncertaintyService/StreamUncertainty"
	UncertaintyService_StreamTrigger_FullMethodName     = "/metacore.module2.v1.UncertaintyService/StreamTrigger"
	UncertaintyService_Health_FullMethodName            = "/metacore.module2.v1.UncertaintyService/Health"
)

// UncertaintyServiceClient is the client API for UncertaintyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UncertaintyServiceClient interface {
	StreamUncertainty(ctx context.Context, in *UncertaintyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UncertaintyEstimate], error)
	StreamTrigger(ctx context.Context, in *UncertaintyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompetenceDropTrigger], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*v1.Health, error)
}

type uncertaintyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUncertaintyServiceClient(cc grpc.ClientConnInterface) UncertaintyServiceClient {
	return &uncertaintyServiceClient{cc}
}

func (c *uncertaintyServiceClient) StreamUncertainty(ctx context.Context, in *UncertaintyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UncertaintyEstimate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UncertaintyService_ServiceDesc.Streams[0], UncertaintyService_StreamUncertainty_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UncertaintyRequest, UncertaintyEstimate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UncertaintyService_StreamUncertaintyClient = grpc.ServerStreamingClient[UncertaintyEstimate]

func (c *uncertaintyServiceClient) StreamTrigger(ctx context.Context, in *UncertaintyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompetenceDropTrigger], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UncertaintyService_ServiceDesc.Streams[1], UncertaintyService_StreamTrigger_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UncertaintyRequest, CompetenceDropTrigger]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UncertaintyService_StreamTriggerClient = grpc.ServerStreamingClient[CompetenceDropTrigger]

func (c *uncertaintyServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*v1.Health, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Health)
	err := c.cc.Invoke(ctx, UncertaintyService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UncertaintyServiceServer is the server API for UncertaintyService service.
// All implementations must embed UnimplementedUncertaintyServiceServer
// for forward compatibility.
type UncertaintyServiceServer interface {
	StreamUncertainty(*UncertaintyRequest, grpc.ServerStreamingServer[UncertaintyEstimate]) error
	StreamTrigger(*UncertaintyRequest, grpc.ServerStreamingServer[CompetenceDropTrigger]) error
	Health(context.Context, *HealthRequest) (*v1.Health, error)
	mustEmbedUnimplementedUncertaintyServiceServer()
}

// UnimplementedUncertaintyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUncertaintyServiceServer struct{}

func (UnimplementedUncertaintyServiceServer) StreamUncertainty(*UncertaintyRequest, grpc.ServerStreamingServer[UncertaintyEstimate]) error {
	return status.Error(codes.Unimplemented, "method StreamUncertainty not implemented")
}
func (UnimplementedUncertaintyServiceServer) StreamTrigger(*UncertaintyRequest, grpc.ServerStreamingServer[CompetenceDropTrigger]) error {
	return status.Error(codes.Unimplemented, "method StreamTrigger not implemented")
}
func (UnimplementedUncertaintyServiceServer) Health(context.Context, *HealthRequest) (*v1.Health, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedUncertaintyServiceServer) mustEmbedUnimplementedUncertaintyServiceServer() {}
func (UnimplementedUncertaintyServiceServer) testEmbeddedByValue()                            {}

// UnsafeUncertaintyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UncertaintyServiceServer will
// result in compilation errors.
type UnsafeUncertaintyServiceServer interface {
	mustEmbedUnimplementedUncertaintyServiceServer()
}

func RegisterUncertaintyServiceServer(s grpc.ServiceRegistrar, srv UncertaintyServiceServer) {
	// If the following call panics, it indicates UnimplementedUncertaintyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UncertaintyService_ServiceDesc, srv)
}

func _UncertaintyService_StreamUncertainty_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UncertaintyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UncertaintyServiceServer).StreamUncertainty(m, &grpc.GenericServerStream[UncertaintyRequest, UncertaintyEstimate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UncertaintyService_StreamUncertaintyServer = grpc.ServerStreamingServer[UncertaintyEstimate]

func _UncertaintyService_StreamTrigger_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UncertaintyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UncertaintyServiceServer).StreamTrigger(m, &grpc.GenericServerStream[UncertaintyRequest, CompetenceDropTrigger]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UncertaintyService_StreamTriggerServer = grpc.ServerStreamingServer[CompetenceDropTrigger]

func _UncertaintyService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UncertaintyServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UncertaintyService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UncertaintyServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UncertaintyService_ServiceDesc is the grpc.ServiceDesc for UncertaintyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UncertaintyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metacore.module2.v1.UncertaintyService",
	HandlerType: (*UncertaintyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _UncertaintyService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUncertainty",
			Handler:       _UncertaintyService_StreamUncertainty_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTrigger",
			Handler:       _UncertaintyService_StreamTrigger_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "module2.proto",
}
