// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: verification.proto

// Module 4 — Abductive Physics-Informed Verification & Semantic Translation.
// Owner: Hariswara S. (IT23291782). Consumers: M3 (verdict), M2 (rejection trace), dashboard.
//
// DETERMINISTIC. The verdict is produced by an OpenDSS power-flow solve against a safety
// specification. Nothing in the decision path is learned.

package verificationv1

import (
	v1 "github.com/metacore/contracts/go/common/v1"
	v11 "github.com/metacore/contracts/go/module3/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_APPROVE     Decision = 1
	Decision_DECISION_REJECT      Decision = 2
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_APPROVE",
		2: "DECISION_REJECT",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_APPROVE":     1,
		"DECISION_REJECT":      2,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_verification_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_verification_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{0}
}

type ViolationType int32

const (
	ViolationType_VIOLATION_TYPE_UNSPECIFIED      ViolationType = 0
	ViolationType_VIOLATION_TYPE_UNDERVOLTAGE     ViolationType = 1
	ViolationType_VIOLATION_TYPE_OVERVOLTAGE      ViolationType = 2
	ViolationType_VIOLATION_TYPE_THERMAL_OVERLOAD ViolationType = 3
	ViolationType_VIOLATION_TYPE_NON_CONVERGENCE  ViolationType = 4
	ViolationType_VIOLATION_TYPE_MALFORMED_ACTION ViolationType = 5
)

// Enum value maps for ViolationType.
var (
	ViolationType_name = map[int32]string{
		0: "VIOLATION_TYPE_UNSPECIFIED",
		1: "VIOLATION_TYPE_UNDERVOLTAGE",
		2: "VIOLATION_TYPE_OVERVOLTAGE",
		3: "VIOLATION_TYPE_THERMAL_OVERLOAD",
		4: "VIOLATION_TYPE_NON_CONVERGENCE",
		5: "VIOLATION_TYPE_MALFORMED_ACTION",
	}
	ViolationType_value = map[string]int32{
		"VIOLATION_TYPE_UNSPECIFIED":      0,
		"VIOLATION_TYPE_UNDERVOLTAGE":     1,
		"VIOLATION_TYPE_OVERVOLTAGE":      2,
		"VIOLATION_TYPE_THERMAL_OVERLOAD": 3,
		"VIOLATION_TYPE_NON_CONVERGENCE":  4,
		"VIOLATION_TYPE_MALFORMED_ACTION": 5,
	}
)

func (x ViolationType) Enum() *ViolationType {
	p := new(ViolationType)
	*p = x
	return p
}

func (x ViolationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViolationType) Descriptor() protoreflect.EnumDescriptor {
	return file_verification_proto_enumTypes[1].Descriptor()
}

func (ViolationType) Type() protoreflect.EnumType {
	return &file_verification_proto_enumTypes[1]
}

func (x ViolationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViolationType.Descriptor instead.
func (ViolationType) EnumDescriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{1}
}

type Generator int32

const (
	Generator_GENERATOR_UNSPECIFIED Generator = 0
	Generator_GENERATOR_TEMPLATE    Generator = 1 // deterministic, the default
	Generator_GENERATOR_CONSTRAINED Generator = 2 // learned but grounding-checked; never part of the decision
)

// Enum value maps for Generator.
var (
	Generator_name = map[int32]string{
		0: "GENERATOR_UNSPECIFIED",
		1: "GENERATOR_TEMPLATE",
		2: "GENERATOR_CONSTRAINED",
	}
	Generator_value = map[string]int32{
		"GENERATOR_UNSPECIFIED": 0,
		"GENERATOR_TEMPLATE":    1,
		"GENERATOR_CONSTRAINED": 2,
	}
)

func (x Generator) Enum() *Generator {
	p := new(Generator)
	*p = x
	return p
}

func (x Generator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Generator) Descriptor() protoreflect.EnumDescriptor {
	return file_verification_proto_enumTypes[2].Descriptor()
}

func (Generator) Type() protoreflect.EnumType {
	return &file_verification_proto_enumTypes[2]
}

func (x Generator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Generator.Descriptor instead.
func (Generator) EnumDescriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{2}
}

type VerificationRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Envelope      *v1.Envelope               `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Action        *v11.ProposedControlAction `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TopologyId    string                     `protobuf:"bytes,3,opt,name=topology_id,json=topologyId,proto3" json:"topology_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	mi := &file_verification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationRequest) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *VerificationRequest) GetAction() *v11.ProposedControlAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *VerificationRequest) GetTopologyId() string {
	if x != nil {
		return x.TopologyId
	}
	return ""
}

type VerificationVerdict struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Envelope            *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ActionId            string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Decision            Decision               `protobuf:"varint,3,opt,name=decision,proto3,enum=metacore.verification.v1.Decision" json:"decision,omitempty"`
	Violations          []*Violation           `protobuf:"bytes,4,rep,name=violations,proto3" json:"violations,omitempty"` // empty on APPROVE
	SolveLatencyMs      float64                `protobuf:"fixed64,5,opt,name=solve_latency_ms,json=solveLatencyMs,proto3" json:"solve_latency_ms,omitempty"`
	SpecVersion         string                 `protobuf:"bytes,6,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"` // the safety specification this was judged against
	NetworkModelVersion string                 `protobuf:"bytes,7,opt,name=network_model_version,json=networkModelVersion,proto3" json:"network_model_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VerificationVerdict) Reset() {
	*x = VerificationVerdict{}
	mi := &file_verification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationVerdict) ProtoMessage() {}

func (x *VerificationVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationVerdict.ProtoReflect.Descriptor instead.
func (*VerificationVerdict) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationVerdict) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *VerificationVerdict) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *VerificationVerdict) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *VerificationVerdict) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *VerificationVerdict) GetSolveLatencyMs() float64 {
	if x != nil {
		return x.SolveLatencyMs
	}
	return 0
}

func (x *VerificationVerdict) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

func (x *VerificationVerdict) GetNetworkModelVersion() string {
	if x != nil {
		return x.NetworkModelVersion
	}
	return ""
}

// Structured violation evidence — the analytical core of the abductive claim, and the payload
// the causal log is generated from. A generated explanation may only reference entities present
// here; anything else is an ungrounded claim.
type Violation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           ViolationType          `protobuf:"varint,1,opt,name=type,proto3,enum=metacore.verification.v1.ViolationType" json:"type,omitempty"`
	ElementId      string                 `protobuf:"bytes,2,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"` // offending bus or line
	Measured       float64                `protobuf:"fixed64,3,opt,name=measured,proto3" json:"measured,omitempty"`
	Limit          float64                `protobuf:"fixed64,4,opt,name=limit,proto3" json:"limit,omitempty"`
	MarginFraction float64                `protobuf:"fixed64,5,opt,name=margin_fraction,json=marginFraction,proto3" json:"margin_fraction,omitempty"` // signed: how far past the limit
	// Which part of the proposed action most plausibly caused this (attribution, not certainty).
	AttributedComponent string `protobuf:"bytes,6,opt,name=attributed_component,json=attributedComponent,proto3" json:"attributed_component,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Violation) Reset() {
	*x = Violation{}
	mi := &file_verification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Violation) ProtoMessage() {}

func (x *Violation) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Violation.ProtoReflect.Descriptor instead.
func (*Violation) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{2}
}

func (x *Violation) GetType() ViolationType {
	if x != nil {
		return x.Type
	}
	return ViolationType_VIOLATION_TYPE_UNSPECIFIED
}

func (x *Violation) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *Violation) GetMeasured() float64 {
	if x != nil {
		return x.Measured
	}
	return 0
}

func (x *Violation) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Violation) GetMarginFraction() float64 {
	if x != nil {
		return x.MarginFraction
	}
	return 0
}

func (x *Violation) GetAttributedComponent() string {
	if x != nil {
		return x.AttributedComponent
	}
	return ""
}

// M4 -> M2. Feeds back into the competence signal so a rejection informs future uncertainty.
type RejectionTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ActionId      string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Violations    []*Violation           `protobuf:"bytes,3,rep,name=violations,proto3" json:"violations,omitempty"`
	Severity      float32                `protobuf:"fixed32,4,opt,name=severity,proto3" json:"severity,omitempty"` // 0..1, derived from margin_fraction across violations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectionTrace) Reset() {
	*x = RejectionTrace{}
	mi := &file_verification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectionTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectionTrace) ProtoMessage() {}

func (x *RejectionTrace) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectionTrace.ProtoReflect.Descriptor instead.
func (*RejectionTrace) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{3}
}

func (x *RejectionTrace) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *RejectionTrace) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *RejectionTrace) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *RejectionTrace) GetSeverity() float32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

// M4 -> operator dashboard. Grounded in the structured evidence above.
type CausalLog struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Envelope         *v1.Envelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ActionId         string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Text             string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	GroundedEntities []string               `protobuf:"bytes,4,rep,name=grounded_entities,json=groundedEntities,proto3" json:"grounded_entities,omitempty"` // must be a subset of the violation element_ids
	Generator        Generator              `protobuf:"varint,5,opt,name=generator,proto3,enum=metacore.verification.v1.Generator" json:"generator,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CausalLog) Reset() {
	*x = CausalLog{}
	mi := &file_verification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CausalLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CausalLog) ProtoMessage() {}

func (x *CausalLog) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CausalLog.ProtoReflect.Descriptor instead.
func (*CausalLog) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{4}
}

func (x *CausalLog) GetEnvelope() *v1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *CausalLog) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *CausalLog) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CausalLog) GetGroundedEntities() []string {
	if x != nil {
		return x.GroundedEntities
	}
	return nil
}

func (x *CausalLog) GetGenerator() Generator {
	if x != nil {
		return x.Generator
	}
	return Generator_GENERATOR_UNSPECIFIED
}

type RejectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *v1.ScenarioRef        `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectionRequest) Reset() {
	*x = RejectionRequest{}
	mi := &file_verification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectionRequest) ProtoMessage() {}

func (x *RejectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectionRequest.ProtoReflect.Descriptor instead.
func (*RejectionRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{5}
}

func (x *RejectionRequest) GetScenario() *v1.ScenarioRef {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_verification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{6}
}

var File_verification_proto protoreflect.FileDescriptor

const file_verification_proto_rawDesc = "" +
	"\n" +
	"\x12verification.proto\x12\x18metacore.verification.v1\x1a\fcommon.proto\x1a\rmodule3.proto\"\xb4\x01\n" +
	"\x13VerificationRequest\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12B\n" +
	"\x06action\x18\x02 \x01(\v2*.metacore.module3.v1.ProposedControlActionR\x06action\x12\x1f\n" +
	"\vtopology_id\x18\x03 \x01(\tR\n" +
	"topologyId\"\xf2\x02\n" +
	"\x13VerificationVerdict\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12>\n" +
	"\bdecision\x18\x03 \x01(\x0e2\".metacore.verification.v1.DecisionR\bdecision\x12C\n" +
	"\n" +
	"violations\x18\x04 \x03(\v2#.metacore.verification.v1.ViolationR\n" +
	"violations\x12(\n" +
	"\x10solve_latency_ms\x18\x05 \x01(\x01R\x0esolveLatencyMs\x12!\n" +
	"\fspec_version\x18\x06 \x01(\tR\vspecVersion\x122\n" +
	"\x15network_model_version\x18\a \x01(\tR\x13networkModelVersion\"\xf5\x01\n" +
	"\tViolation\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.metacore.verification.v1.ViolationTypeR\x04type\x12\x1d\n" +
	"\n" +
	"element_id\x18\x02 \x01(\tR\telementId\x12\x1a\n" +
	"\bmeasured\x18\x03 \x01(\x01R\bmeasured\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x01R\x05limit\x12'\n" +
	"\x0fmargin_fraction\x18\x05 \x01(\x01R\x0emarginFraction\x121\n" +
	"\x14attributed_component\x18\x06 \x01(\tR\x13attributedComponent\"\xc8\x01\n" +
	"\x0eRejectionTrace\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12C\n" +
	"\n" +
	"violations\x18\x03 \x03(\v2#.metacore.verification.v1.ViolationR\n" +
	"violations\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\x02R\bseverity\"\xe6\x01\n" +
	"\tCausalLog\x128\n" +
	"\benvelope\x18\x01 \x01(\v2\x1c.metacore.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12+\n" +
	"\x11grounded_entities\x18\x04 \x03(\tR\x10groundedEntities\x12A\n" +
	"\tgenerator\x18\x05 \x01(\x0e2#.metacore.verification.v1.GeneratorR\tgenerator\"O\n" +
	"\x10RejectionRequest\x12;\n" +
	"\bscenario\x18\x01 \x01(\v2\x1f.metacore.common.v1.ScenarioRefR\bscenario\"\x0f\n" +
	"\rHealthRequest*O\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DECISION_APPROVE\x10\x01\x12\x13\n" +
	"\x0fDECISION_REJECT\x10\x02*\xde\x01\n" +
	"\rViolationType\x12\x1e\n" +
	"\x1aVIOLATION_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVIOLATION_TYPE_UNDERVOLTAGE\x10\x01\x12\x1e\n" +
	"\x1aVIOLATION_TYPE_OVERVOLTAGE\x10\x02\x12#\n" +
	"\x1fVIOLATION_TYPE_THERMAL_OVERLOAD\x10\x03\x12\"\n" +
	"\x1eVIOLATION_TYPE_NON_CONVERGENCE\x10\x04\x12#\n" +
	"\x1fVIOLATION_TYPE_MALFORMED_ACTION\x10\x05*Y\n" +
	"\tGenerator\x12\x19\n" +
	"\x15GENERATOR_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12GENERATOR_TEMPLATE\x10\x01\x12\x19\n" +
	"\x15GENERATOR_CONSTRAINED\x10\x022\x9f\x03\n" +
	"\x13VerificationService\x12f\n" +
	"\x06Verify\x12-.metacore.verification.v1.VerificationRequest\x1a-.metacore.verification.v1.VerificationVerdict\x12j\n" +
	"\x10StreamRejections\x12*.metacore.verification.v1.RejectionRequest\x1a(.metacore.verification.v1.RejectionTrace0\x01\x12e\n" +
	"\x10StreamCausalLogs\x12*.metacore.verification.v1.RejectionRequest\x1a#.metacore.verification.v1.CausalLog0\x01\x12M\n" +
	"\x06Health\x12'.metacore.verification.v1.HealthRequest\x1a\x1a.metacore.common.v1.HealthB\xf4\x01\n" +
	"\x1ccom.metacore.verification.v1B\x11VerificationProtoP\x01Z?github.com/metacore/contracts/go/verification/v1;verificationv1\xa2\x02\x03MVX\xaa\x02\x18Metacore.Verification.V1\xca\x02\x18Metacore\\Verification\\V1\xe2\x02$Metacore\\Verification\\V1\\GPBMetadata\xea\x02\x1aMetacore::Verification::V1b\x06proto3"

var (
	file_verification_proto_rawDescOnce sync.Once
	file_verification_proto_rawDescData []byte
)

func file_verification_proto_rawDescGZIP() []byte {
	file_verification_proto_rawDescOnce.Do(func() {
		file_verification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verification_proto_rawDesc), len(file_verification_proto_rawDesc)))
	})
	return file_verification_proto_rawDescData
}

var file_verification_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_verification_proto_goTypes = []any{
	(Decision)(0),                     // 0: metacore.verification.v1.Decision
	(ViolationType)(0),                // 1: metacore.verification.v1.ViolationType
	(Generator)(0),                    // 2: metacore.verification.v1.Generator
	(*VerificationRequest)(nil),       // 3: metacore.verification.v1.VerificationRequest
	(*VerificationVerdict)(nil),       // 4: metacore.verification.v1.VerificationVerdict
	(*Violation)(nil),                 // 5: metacore.verification.v1.Violation
	(*RejectionTrace)(nil),            // 6: metacore.verification.v1.RejectionTrace
	(*CausalLog)(nil),                 // 7: metacore.verification.v1.CausalLog
	(*RejectionRequest)(nil),          // 8: metacore.verification.v1.RejectionRequest
	(*HealthRequest)(nil),             // 9: metacore.verification.v1.HealthRequest
	(*v1.Envelope)(nil),               // 10: metacore.common.v1.Envelope
	(*v11.ProposedControlAction)(nil), // 11: metacore.module3.v1.ProposedControlAction
	(*v1.ScenarioRef)(nil),            // 12: metacore.common.v1.ScenarioRef
	(*v1.Health)(nil),                 // 13: metacore.common.v1.Health
}
var file_verification_proto_depIdxs = []int32{
	10, // 0: metacore.verification.v1.VerificationRequest.envelope:type_name -> metacore.common.v1.Envelope
	11, // 1: metacore.verification.v1.VerificationRequest.action:type_name -> metacore.module3.v1.ProposedControlAction
	10, // 2: metacore.verification.v1.VerificationVerdict.envelope:type_name -> metacore.common.v1.Envelope
	0,  // 3: metacore.verification.v1.VerificationVerdict.decision:type_name -> metacore.verification.v1.Decision
	5,  // 4: metacore.verification.v1.VerificationVerdict.violations:type_name -> metacore.verification.v1.Violation
	1,  // 5: metacore.verification.v1.Violation.type:type_name -> metacore.verification.v1.ViolationType
	10, // 6: metacore.verification.v1.RejectionTrace.envelope:type_name -> metacore.common.v1.Envelope
	5,  // 7: metacore.verification.v1.RejectionTrace.violations:type_name -> metacore.verification.v1.Violation
	10, // 8: metacore.verification.v1.CausalLog.envelope:type_name -> metacore.common.v1.Envelope
	2,  // 9: metacore.verification.v1.CausalLog.generator:type_name -> metacore.verification.v1.Generator
	12, // 10: metacore.verification.v1.RejectionRequest.scenario:type_name -> metacore.common.v1.ScenarioRef
	3,  // 11: metacore.verification.v1.VerificationService.Verify:input_type -> metacore.verification.v1.VerificationRequest
	8,  // 12: metacore.verification.v1.VerificationService.StreamRejections:input_type -> metacore.verification.v1.RejectionRequest
	8,  // 13: metacore.verification.v1.VerificationService.StreamCausalLogs:input_type -> metacore.verification.v1.RejectionRequest
	9,  // 14: metacore.verification.v1.VerificationService.Health:input_type -> metacore.verification.v1.HealthRequest
	4,  // 15: metacore.verification.v1.VerificationService.Verify:output_type -> metacore.verification.v1.VerificationVerdict
	6,  // 16: metacore.verification.v1.VerificationService.StreamRejections:output_type -> metacore.verification.v1.RejectionTrace
	7,  // 17: metacore.verification.v1.VerificationService.StreamCausalLogs:output_type -> metacore.verification.v1.CausalLog
	13, // 18: metacore.verification.v1.VerificationService.Health:output_type -> metacore.common.v1.Health
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_verification_proto_init() }
func file_verification_proto_init() {
	if File_verification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verification_proto_rawDesc), len(file_verification_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verification_proto_goTypes,
		DependencyIndexes: file_verification_proto_depIdxs,
		EnumInfos:         file_verification_proto_enumTypes,
		MessageInfos:      file_verification_proto_msgTypes,
	}.Build()
	File_verification_proto = out.File
	file_verification_proto_goTypes = nil
	file_verification_proto_depIdxs = nil
}
