// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: verification.proto

// Module 4 — Abductive Physics-Informed Verification & Semantic Translation.
// Owner: Hariswara S. (IT23291782). Consumers: M3 (verdict), M2 (rejection trace), dashboard.
//
// DETERMINISTIC. The verdict is produced by an OpenDSS power-flow solve against a safety
// specification. Nothing in the decision path is learned.

package verificationv1

import (
	context "context"
	v1 "github.com/metacore/contracts/go/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerificationService_Verify_FullMethodName           = "/metacore.verification.v1.VerificationService/Verify"
	VerificationService_StreamRejections_FullMethodName = "/metacore.verification.v1.VerificationService/StreamRejections"
	VerificationService_StreamCausalLogs_FullMethodName = "/metacore.verification.v1.VerificationService/StreamCausalLogs"
	VerificationService_Health_FullMethodName           = "/metacore.verification.v1.VerificationService/Health"
)

// VerificationServiceClient is the client API for VerificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerificationServiceClient interface {
	// Blocking. The orchestrator waits on this; the firewall is not bypassable.
	Verify(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*VerificationVerdict, error)
	StreamRejections(ctx context.Context, in *RejectionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RejectionTrace], error)
	StreamCausalLogs(ctx context.Context, in *RejectionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CausalLog], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*v1.Health, error)
}

type verificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerificationServiceClient(cc grpc.ClientConnInterface) VerificationServiceClient {
	return &verificationServiceClient{cc}
}

func (c *verificationServiceClient) Verify(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*VerificationVerdict, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationVerdict)
	err := c.cc.Invoke(ctx, VerificationService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationServiceClient) StreamRejections(ctx context.Context, in *RejectionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RejectionTrace], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VerificationService_ServiceDesc.Streams[0], VerificationService_StreamRejections_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RejectionRequest, RejectionTrace]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VerificationService_StreamRejectionsClient = grpc.ServerStreamingClient[RejectionTrace]

func (c *verificationServiceClient) StreamCausalLogs(ctx context.Context, in *RejectionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CausalLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VerificationService_ServiceDesc.Streams[1], VerificationService_StreamCausalLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RejectionRequest, CausalLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VerificationService_StreamCausalLogsClient = grpc.ServerStreamingClient[CausalLog]

func (c *verificationServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*v1.Health, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Health)
	err := c.cc.Invoke(ctx, VerificationService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationServiceServer is the server API for VerificationService service.
// All implementations must embed UnimplementedVerificationServiceServer
// for forward compatibility.
type VerificationServiceServer interface {
	// Blocking. The orchestrator waits on this; the firewall is not bypassable.
	Verify(context.Context, *VerificationRequest) (*VerificationVerdict, error)
	StreamRejections(*RejectionRequest, grpc.ServerStreamingServer[RejectionTrace]) error
	StreamCausalLogs(*RejectionRequest, grpc.ServerStreamingServer[CausalLog]) error
	Health(context.Context, *HealthRequest) (*v1.Health, error)
	mustEmbedUnimplementedVerificationServiceServer()
}

// UnimplementedVerificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerificationServiceServer struct{}

func (UnimplementedVerificationServiceServer) Verify(context.Context, *VerificationRequest) (*VerificationVerdict, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedVerificationServiceServer) StreamRejections(*RejectionRequest, grpc.ServerStreamingServer[RejectionTrace]) error {
	return status.Error(codes.Unimplemented, "method StreamRejections not implemented")
}
func (UnimplementedVerificationServiceServer) StreamCausalLogs(*RejectionRequest, grpc.ServerStreamingServer[CausalLog]) error {
	return status.Error(codes.Unimplemented, "method StreamCausalLogs not implemented")
}
func (UnimplementedVerificationServiceServer) Health(context.Context, *HealthRequest) (*v1.Health, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedVerificationServiceServer) mustEmbedUnimplementedVerificationServiceServer() {}
func (UnimplementedVerificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeVerificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerificationServiceServer will
// result in compilation errors.
type UnsafeVerificationServiceServer interface {
	mustEmbedUnimplementedVerificationServiceServer()
}

func RegisterVerificationServiceServer(s grpc.ServiceRegistrar, srv VerificationServiceServer) {
	// If the following call panics, it indicates UnimplementedVerificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerificationService_ServiceDesc, srv)
}

func _VerificationService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationServiceServer).Verify(ctx, req.(*VerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationService_StreamRejections_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RejectionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VerificationServiceServer).StreamRejections(m, &grpc.GenericServerStream[RejectionRequest, RejectionTrace]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VerificationService_StreamRejectionsServer = grpc.ServerStreamingServer[RejectionTrace]

func _VerificationService_StreamCausalLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RejectionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VerificationServiceServer).StreamCausalLogs(m, &grpc.GenericServerStream[RejectionRequest, CausalLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VerificationService_StreamCausalLogsServer = grpc.ServerStreamingServer[CausalLog]

func _VerificationService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerificationService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerificationService_ServiceDesc is the grpc.ServiceDesc for VerificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metacore.verification.v1.VerificationService",
	HandlerType: (*VerificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _VerificationService_Verify_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _VerificationService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRejections",
			Handler:       _VerificationService_StreamRejections_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCausalLogs",
			Handler:       _VerificationService_StreamCausalLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "verification.proto",
}
